<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Color;
use App\Models\PrintPlacement;
use App\Models\PrintSide;
use App\Models\Size;
use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Create Admin User
        User::updateOrCreate(['email' => 'deepinart@gmail.com'], [
            'name' => 'Alin-Constantin Ivana',
            'password' => bcrypt('adelante'),
            'role' => User::ROLE_ADMIN,
            'is_active' => true,
        ]);

        // Seed Print Placements
        PrintPlacement::updateOrCreate(['name' => 'Fronte'], ['description' => 'Stampa sul fronte 23x30 cm', 'sort_order' => 1, 'default_price' => 3]);
        PrintPlacement::updateOrCreate(['name' => 'Dietro'], ['description' => 'Stampa sul dietro 23x30 cm', 'sort_order' => 2, 'default_price' => 3]);
        PrintPlacement::updateOrCreate(['name' => 'Manica Sinistra'], ['description' => 'Stampa sulla manica sinistra 9x9 cm', 'sort_order' => 3, 'default_price' => 2]);
        PrintPlacement::updateOrCreate(['name' => 'Manica Destra'], ['description' => 'Stampa sulla manica destra 9x9 cm', 'sort_order' => 4, 'default_price' => 2]);
        PrintPlacement::updateOrCreate(['name' => 'Lato Cuore'], ['description' => 'Stampa sul lato cuore 9x9 cm', 'sort_order' => 5, 'default_price' => 1.80]);
        PrintPlacement::updateOrCreate(['name' => 'Tasca'], ['description' => 'Stampa sulla tasca 9x9 cm', 'sort_order' => 6, 'default_price' => 2]);
        PrintPlacement::updateOrCreate(['name' => 'Gamba sinistra'], ['description' => 'Stampa sulla gamba sinistra 9x9 cm', 'sort_order' => 7, 'default_price' => 2]);
        PrintPlacement::updateOrCreate(['name' => 'Gamba destra'], ['description' => 'Stampa sulla gamba destra 9x9 cm', 'sort_order' => 8, 'default_price' => 2]);

        // Seed Print Sides
        PrintSide::updateOrCreate(['name' => 'Stampa sul fronte'], ['description' => 'Stampa solo sul fronte', 'sort_order' => 1]);
        PrintSide::updateOrCreate(['name' => 'Fronte e retro uguali'], ['description' => 'Stampa fronte e retro uguali', 'sort_order' => 2]);
        PrintSide::updateOrCreate(['name' => 'Fronte e retro differenti'], ['description' => 'Stampa fronte e retro differenti', 'sort_order' => 3]);

        // Categories
        Category::updateOrCreate(['slug' => 'abbigliamento-da-lavoro'], ['name' => 'Abbigliamento da lavoro', 'parent_id' => null]);
        Category::updateOrCreate(['slug' => 't-shirt'], ['name' => 'T-Shirt', 'parent_id' => 1]);
        Category::updateOrCreate(['slug' => 'polo'], ['name' => 'Polo', 'parent_id' => 1]);
        Category::updateOrCreate(['slug' => 'felpe'], ['name' => 'Felpe', 'parent_id' => 1]);
        Category::updateOrCreate(['slug' => 'pantaloni'], ['name' => 'Pantaloni', 'parent_id' => 1]);
        Category::updateOrCreate(['slug' => 'giacche'], ['name' => 'Giacche', 'parent_id' => 1]);
        Category::updateOrCreate(['slug' => 'gilet'], ['name' => 'Gilet', 'parent_id' => 1]);
        Category::updateOrCreate(['slug' => 'calzature'], ['name' => 'Calzature', 'parent_id' => 1]);

        // Seed Sizes
        Size::updateOrCreate(['size' => 'XXS', 'size_code' => '2'], ['size_name' => 'XXS', 'sort_order' => 1]);
        Size::updateOrCreate(['size' => 'XS', 'size_code' => '3'], ['size_name' => 'XS', 'sort_order' => 2]);
        Size::updateOrCreate(['size' => 'UK 03', 'size_code' => '03'], ['size_name' => 'UK 03', 'sort_order' => 3]);
        Size::updateOrCreate(['size' => 'S', 'size_code' => '4'], ['size_name' => 'S', 'sort_order' => 4]);
        Size::updateOrCreate(['size' => 'UK 04', 'size_code' => '04'], ['size_name' => 'UK 04', 'sort_order' => 5]);
        Size::updateOrCreate(['size' => 'M', 'size_code' => '5'], ['size_name' => 'M', 'sort_order' => 6]);
        Size::updateOrCreate(['size' => 'UK 05', 'size_code' => '05'], ['size_name' => 'UK 05', 'sort_order' => 7]);
        Size::updateOrCreate(['size' => 'L', 'size_code' => '6'], ['size_name' => 'L', 'sort_order' => 8]);
        Size::updateOrCreate(['size' => 'UK 06', 'size_code' => '06'], ['size_name' => 'UK 06', 'sort_order' => 9]);
        Size::updateOrCreate(['size' => 'XL', 'size_code' => '7'], ['size_name' => 'XL', 'sort_order' => 10]);
        Size::updateOrCreate(['size' => 'UK 07', 'size_code' => '07'], ['size_name' => 'UK 07', 'sort_order' => 11]);
        Size::updateOrCreate(['size' => 'XXL', 'size_code' => '8'], ['size_name' => 'XXL', 'sort_order' => 12]);
        Size::updateOrCreate(['size' => 'UK 08', 'size_code' => '08'], ['size_name' => 'UK 08', 'sort_order' => 13]);
        Size::updateOrCreate(['size' => '3XL', 'size_code' => '9'], ['size_name' => '3XL', 'sort_order' => 14]);
        Size::updateOrCreate(['size' => 'UK 09', 'size_code' => '09'], ['size_name' => 'UK 09', 'sort_order' => 15]);
        Size::updateOrCreate(['size' => '4XL', 'size_code' => '10'], ['size_name' => '4XL', 'sort_order' => 16]);
        Size::updateOrCreate(['size' => 'UK 10,5', 'size_code' => '10,5'], ['size_name' => 'UK 10,5', 'sort_order' => 17]);
        Size::updateOrCreate(['size' => '5XL', 'size_code' => '11'], ['size_name' => '5XL', 'sort_order' => 18]);
        Size::updateOrCreate(['size' => 'UK 11,5', 'size_code' => '11,5'], ['size_name' => 'UK 11,5', 'sort_order' => 19]);
        Size::updateOrCreate(['size' => '6XL', 'size_code' => '12'], ['size_name' => '6XL', 'sort_order' => 20]);
        Size::updateOrCreate(['size' => 'UK 12,5', 'size_code' => '12,5'], ['size_name' => 'UK 12,5', 'sort_order' => 21]);
        Size::updateOrCreate(['size' => 'UK 13', 'size_code' => '13'], ['size_name' => 'UK 13', 'sort_order' => 22]);
        Size::updateOrCreate(['size' => 'UK 14', 'size_code' => '14'], ['size_name' => 'UK 14', 'sort_order' => 23]);
        Size::updateOrCreate(['size' => 'UK 15', 'size_code' => '15'], ['size_name' => 'UK 15', 'sort_order' => 24]);
        Size::updateOrCreate(['size' => '28/30', 'size_code' => '28'], ['size_name' => '28/30', 'sort_order' => 25]);
        Size::updateOrCreate(['size' => '30"', 'size_code' => '30'], ['size_name' => '30"', 'sort_order' => 26]);
        Size::updateOrCreate(['size' => '31"', 'size_code' => '31'], ['size_name' => '31"', 'sort_order' => 27]);
        Size::updateOrCreate(['size' => 'C32', 'size_code' => '32'], ['size_name' => 'C32', 'sort_order' => 28]);
        Size::updateOrCreate(['size' => '33"', 'size_code' => '33'], ['size_name' => '33"', 'sort_order' => 29]);
        Size::updateOrCreate(['size' => 'C34', 'size_code' => '34'], ['size_name' => 'C34', 'sort_order' => 30]);
        Size::updateOrCreate(['size' => '35-37', 'size_code' => '35'], ['size_name' => '35-37', 'sort_order' => 31]);
        Size::updateOrCreate(['size' => 'C36', 'size_code' => '36'], ['size_name' => 'C36', 'sort_order' => 32]);
        Size::updateOrCreate(['size' => 'SIZE 37', 'size_code' => '37'], ['size_name' => 'SIZE 37', 'sort_order' => 33]);
        Size::updateOrCreate(['size' => 'C38', 'size_code' => '38'], ['size_name' => 'C38', 'sort_order' => 34]);
        Size::updateOrCreate(['size' => 'SIZE 39', 'size_code' => '39'], ['size_name' => 'SIZE 39', 'sort_order' => 35]);
        Size::updateOrCreate(['size' => 'C40', 'size_code' => '40'], ['size_name' => 'C40', 'sort_order' => 36]);
        Size::updateOrCreate(['size' => 'SIZE 41', 'size_code' => '41'], ['size_name' => 'SIZE 41', 'sort_order' => 37]);
        Size::updateOrCreate(['size' => 'C42', 'size_code' => '42'], ['size_name' => 'C42', 'sort_order' => 38]);
        Size::updateOrCreate(['size' => 'SIZE 43', 'size_code' => '43'], ['size_name' => 'SIZE 43', 'sort_order' => 39]);
        Size::updateOrCreate(['size' => 'C44', 'size_code' => '44'], ['size_name' => 'C44', 'sort_order' => 40]);
        Size::updateOrCreate(['size' => 'SIZE 45', 'size_code' => '45'], ['size_name' => 'SIZE 45', 'sort_order' => 41]);
        Size::updateOrCreate(['size' => 'C46', 'size_code' => '46'], ['size_name' => 'C46', 'sort_order' => 42]);
        Size::updateOrCreate(['size' => 'SIZE 47', 'size_code' => '47'], ['size_name' => 'SIZE 47', 'sort_order' => 43]);
        Size::updateOrCreate(['size' => 'C48', 'size_code' => '48'], ['size_name' => 'C48', 'sort_order' => 44]);
        Size::updateOrCreate(['size' => 'C50', 'size_code' => '50'], ['size_name' => 'C50', 'sort_order' => 45]);
        Size::updateOrCreate(['size' => 'C52', 'size_code' => '52'], ['size_name' => 'C52', 'sort_order' => 46]);
        Size::updateOrCreate(['size' => 'C54', 'size_code' => '54'], ['size_name' => 'C54', 'sort_order' => 47]);
        Size::updateOrCreate(['size' => 'C56', 'size_code' => '56'], ['size_name' => 'C56', 'sort_order' => 48]);
        Size::updateOrCreate(['size' => 'C58', 'size_code' => '58'], ['size_name' => 'C58', 'sort_order' => 49]);
        Size::updateOrCreate(['size' => 'C60', 'size_code' => '60'], ['size_name' => 'C60', 'sort_order' => 50]);
        Size::updateOrCreate(['size' => 'C62', 'size_code' => '62'], ['size_name' => 'C62', 'sort_order' => 51]);
        Size::updateOrCreate(['size' => 'C64', 'size_code' => '64'], ['size_name' => 'C64', 'sort_order' => 52]);
        Size::updateOrCreate(['size' => '85 CM.', 'size_code' => '70'], ['size_name' => '85 CM.', 'sort_order' => 53]);
        Size::updateOrCreate(['size' => 'D84', 'size_code' => '84'], ['size_name' => 'D84', 'sort_order' => 54]);
        Size::updateOrCreate(['size' => '100 CM.', 'size_code' => '85'], ['size_name' => '100 CM.', 'sort_order' => 55]);
        Size::updateOrCreate(['size' => 'D88', 'size_code' => '88'], ['size_name' => 'D88', 'sort_order' => 56]);
        Size::updateOrCreate(['size' => 'D92', 'size_code' => '92'], ['size_name' => 'D92', 'sort_order' => 57]);
        Size::updateOrCreate(['size' => '110 CM.', 'size_code' => '95'], ['size_name' => '110 CM.', 'sort_order' => 58]);
        Size::updateOrCreate(['size' => 'D96', 'size_code' => '96'], ['size_name' => 'D96', 'sort_order' => 59]);
        Size::updateOrCreate(['size' => 'D100', 'size_code' => '100'], ['size_name' => 'D100', 'sort_order' => 60]);
        Size::updateOrCreate(['size' => 'D104', 'size_code' => '104'], ['size_name' => 'D104', 'sort_order' => 61]);
        Size::updateOrCreate(['size' => '105 CM', 'size_code' => '105'], ['size_name' => '105 CM', 'sort_order' => 62]);
        Size::updateOrCreate(['size' => 'D108', 'size_code' => '108'], ['size_name' => 'D108', 'sort_order' => 63]);
        Size::updateOrCreate(['size' => '110/116', 'size_code' => '110'], ['size_name' => '110/116', 'sort_order' => 64]);
        Size::updateOrCreate(['size' => 'D112', 'size_code' => '112'], ['size_name' => 'D112', 'sort_order' => 65]);
        Size::updateOrCreate(['size' => 'D116', 'size_code' => '116'], ['size_name' => 'D116', 'sort_order' => 66]);
        Size::updateOrCreate(['size' => 'D120', 'size_code' => '120'], ['size_name' => 'D120', 'sort_order' => 67]);
        Size::updateOrCreate(['size' => '122/128', 'size_code' => '122'], ['size_name' => '122/128', 'sort_order' => 68]);
        Size::updateOrCreate(['size' => '122/128', 'size_code' => '128'], ['size_name' => '122/128', 'sort_order' => 69]);
        Size::updateOrCreate(['size' => 'UK 13,5', 'size_code' => '13,5'], ['size_name' => 'UK 13,5', 'sort_order' => 70]);
        Size::updateOrCreate(['size' => '134/140', 'size_code' => '134'], ['size_name' => '134/140', 'sort_order' => 71]);
        Size::updateOrCreate(['size' => '130/140', 'size_code' => '140'], ['size_name' => '130/140', 'sort_order' => 72]);
        Size::updateOrCreate(['size' => 'C142', 'size_code' => '142'], ['size_name' => 'C142', 'sort_order' => 73]);
        Size::updateOrCreate(['size' => 'C144', 'size_code' => '144'], ['size_name' => 'C144', 'sort_order' => 74]);
        Size::updateOrCreate(['size' => 'C146', 'size_code' => '146'], ['size_name' => 'C146', 'sort_order' => 75]);
        Size::updateOrCreate(['size' => 'C148', 'size_code' => '148'], ['size_name' => 'C148', 'sort_order' => 76]);
        Size::updateOrCreate(['size' => 'C150', 'size_code' => '150'], ['size_name' => 'C150', 'sort_order' => 77]);
        Size::updateOrCreate(['size' => 'C152', 'size_code' => '152'], ['size_name' => 'C152', 'sort_order' => 78]);
        Size::updateOrCreate(['size' => 'C154', 'size_code' => '154'], ['size_name' => 'C154', 'sort_order' => 79]);
        Size::updateOrCreate(['size' => 'C156', 'size_code' => '156'], ['size_name' => 'C156', 'sort_order' => 80]);
        Size::updateOrCreate(['size' => '158/164', 'size_code' => '158'], ['size_name' => '158/164', 'sort_order' => 81]);
        Size::updateOrCreate(['size' => 'C160', 'size_code' => '160'], ['size_name' => 'C160', 'sort_order' => 82]);
        Size::updateOrCreate(['size' => 'C162', 'size_code' => '162'], ['size_name' => 'C162', 'sort_order' => 83]);
        Size::updateOrCreate(['size' => 'C164', 'size_code' => '164'], ['size_name' => 'C164', 'sort_order' => 84]);
        Size::updateOrCreate(['size' => '25/32', 'size_code' => '2532'], ['size_name' => '25/32', 'sort_order' => 85]);
        Size::updateOrCreate(['size' => '25/34', 'size_code' => '2534'], ['size_name' => '25/34', 'sort_order' => 86]);
        Size::updateOrCreate(['size' => '26/32', 'size_code' => '2632'], ['size_name' => '26/32', 'sort_order' => 87]);
        Size::updateOrCreate(['size' => '26/34', 'size_code' => '2634'], ['size_name' => '26/34', 'sort_order' => 88]);
        Size::updateOrCreate(['size' => '28/30', 'size_code' => '2830'], ['size_name' => '28/30', 'sort_order' => 89]);
        Size::updateOrCreate(['size' => '28/32', 'size_code' => '2832'], ['size_name' => '28/32', 'sort_order' => 90]);
        Size::updateOrCreate(['size' => '28/34', 'size_code' => '2834'], ['size_name' => '28/34', 'sort_order' => 91]);
        Size::updateOrCreate(['size' => '29/30', 'size_code' => '2930'], ['size_name' => '29/30', 'sort_order' => 92]);
        Size::updateOrCreate(['size' => '29/32', 'size_code' => '2932'], ['size_name' => '29/32', 'sort_order' => 93]);
        Size::updateOrCreate(['size' => '29/34', 'size_code' => '2934'], ['size_name' => '29/34', 'sort_order' => 94]);
        Size::updateOrCreate(['size' => 'UK 3,5', 'size_code' => '3,5'], ['size_name' => 'UK 3,5', 'sort_order' => 95]);
        Size::updateOrCreate(['size' => '30/30', 'size_code' => '3030'], ['size_name' => '30/30', 'sort_order' => 96]);
        Size::updateOrCreate(['size' => '30/32', 'size_code' => '3032'], ['size_name' => '30/32', 'sort_order' => 97]);
        Size::updateOrCreate(['size' => '30/34', 'size_code' => '3034'], ['size_name' => '30/34', 'sort_order' => 98]);
        Size::updateOrCreate(['size' => '31/30', 'size_code' => '3130'], ['size_name' => '31/30', 'sort_order' => 99]);
        Size::updateOrCreate(['size' => '31/32', 'size_code' => '3132'], ['size_name' => '31/32', 'sort_order' => 100]);
        Size::updateOrCreate(['size' => '31/34', 'size_code' => '3134'], ['size_name' => '31/34', 'sort_order' => 101]);
        Size::updateOrCreate(['size' => '32/30', 'size_code' => '3230'], ['size_name' => '32/30', 'sort_order' => 102]);
        Size::updateOrCreate(['size' => '32/32', 'size_code' => '3232'], ['size_name' => '32/32', 'sort_order' => 103]);
        Size::updateOrCreate(['size' => '32/34', 'size_code' => '3234'], ['size_name' => '32/34', 'sort_order' => 104]);
        Size::updateOrCreate(['size' => '32/36', 'size_code' => '3236'], ['size_name' => '32/36', 'sort_order' => 105]);
        Size::updateOrCreate(['size' => '33/30', 'size_code' => '3330'], ['size_name' => '33/30', 'sort_order' => 106]);
        Size::updateOrCreate(['size' => '33/32', 'size_code' => '3332'], ['size_name' => '33/32', 'sort_order' => 107]);
        Size::updateOrCreate(['size' => '33/34', 'size_code' => '3334'], ['size_name' => '33/34', 'sort_order' => 108]);
        Size::updateOrCreate(['size' => '33/36', 'size_code' => '3336'], ['size_name' => '33/36', 'sort_order' => 109]);
        Size::updateOrCreate(['size' => '34/30', 'size_code' => '3430'], ['size_name' => '34/30', 'sort_order' => 110]);
        Size::updateOrCreate(['size' => '34/32', 'size_code' => '3432'], ['size_name' => '34/32', 'sort_order' => 111]);
        Size::updateOrCreate(['size' => '34/34', 'size_code' => '3434'], ['size_name' => '34/34', 'sort_order' => 112]);
        Size::updateOrCreate(['size' => '34/36', 'size_code' => '3436'], ['size_name' => '34/36', 'sort_order' => 113]);
        Size::updateOrCreate(['size' => '35-38', 'size_code' => '3538'], ['size_name' => '35-38', 'sort_order' => 114]);
        Size::updateOrCreate(['size' => '36/30', 'size_code' => '3630'], ['size_name' => '36/30', 'sort_order' => 115]);
        Size::updateOrCreate(['size' => '36/32', 'size_code' => '3632'], ['size_name' => '36/32', 'sort_order' => 116]);
        Size::updateOrCreate(['size' => '36/34', 'size_code' => '3634'], ['size_name' => '36/34', 'sort_order' => 117]);
        Size::updateOrCreate(['size' => '36/36', 'size_code' => '3636'], ['size_name' => '36/36', 'sort_order' => 118]);
        Size::updateOrCreate(['size' => '36-39', 'size_code' => '3639'], ['size_name' => '36-39', 'sort_order' => 119]);
        Size::updateOrCreate(['size' => '38/30', 'size_code' => '3830'], ['size_name' => '38/30', 'sort_order' => 120]);
        Size::updateOrCreate(['size' => '38/32', 'size_code' => '3832'], ['size_name' => '38/32', 'sort_order' => 121]);
        Size::updateOrCreate(['size' => '38/34', 'size_code' => '3834'], ['size_name' => '38/34', 'sort_order' => 122]);
        Size::updateOrCreate(['size' => '38/36', 'size_code' => '3836'], ['size_name' => '38/36', 'sort_order' => 123]);
        Size::updateOrCreate(['size' => '39-42', 'size_code' => '3942'], ['size_name' => '39-42', 'sort_order' => 124]);
        Size::updateOrCreate(['size' => 'UK 4,5', 'size_code' => '4,5'], ['size_name' => 'UK 4,5', 'sort_order' => 125]);
        Size::updateOrCreate(['size' => '40/32', 'size_code' => '4032'], ['size_name' => '40/32', 'sort_order' => 126]);
        Size::updateOrCreate(['size' => '40/34', 'size_code' => '4034'], ['size_name' => '40/34', 'sort_order' => 127]);
        Size::updateOrCreate(['size' => '40/36', 'size_code' => '4036'], ['size_name' => '40/36', 'sort_order' => 128]);
        Size::updateOrCreate(['size' => '40-42', 'size_code' => '4042'], ['size_name' => '40-42', 'sort_order' => 129]);
        Size::updateOrCreate(['size' => '4045', 'size_code' => '4045'], ['size_name' => '4045', 'sort_order' => 130]);
        Size::updateOrCreate(['size' => '42/32', 'size_code' => '4232'], ['size_name' => '42/32', 'sort_order' => 131]);
        Size::updateOrCreate(['size' => '4234', 'size_code' => '4234'], ['size_name' => '4234', 'sort_order' => 132]);
        Size::updateOrCreate(['size' => '4236', 'size_code' => '4236'], ['size_name' => '4236', 'sort_order' => 133]);
        Size::updateOrCreate(['size' => '43-45', 'size_code' => '4345'], ['size_name' => '43-45', 'sort_order' => 134]);
        Size::updateOrCreate(['size' => '43-46', 'size_code' => '4346'], ['size_name' => '43-46', 'sort_order' => 135]);
        Size::updateOrCreate(['size' => '46-48', 'size_code' => '4648'], ['size_name' => '46-48', 'sort_order' => 136]);
        Size::updateOrCreate(['size' => 'UK 5,5', 'size_code' => '5,5'], ['size_name' => 'UK 5,5', 'sort_order' => 137]);
        Size::updateOrCreate(['size' => 'UK 6,5', 'size_code' => '6,5'], ['size_name' => 'UK 6,5', 'sort_order' => 138]);
        Size::updateOrCreate(['size' => 'UK 7,5', 'size_code' => '7,5'], ['size_name' => 'UK 7,5', 'sort_order' => 139]);
        Size::updateOrCreate(['size' => 'UK 8,5', 'size_code' => '8,5'], ['size_name' => 'UK 8,5', 'sort_order' => 140]);
        Size::updateOrCreate(['size' => 'UK 9,5', 'size_code' => '9,5'], ['size_name' => 'UK 9,5', 'sort_order' => 141]);
        Size::updateOrCreate(['size' => 'L/XL', 'size_code' => 'L/XL'], ['size_name' => 'L/XL', 'sort_order' => 142]);
        Size::updateOrCreate(['size' => 'S/M', 'size_code' => 'S/M'], ['size_name' => 'S/M', 'sort_order' => 143]);
        Size::updateOrCreate(['size' => 'S_SWEA', 'size_code' => 'S_SWEA'], ['size_name' => 'S_SWEA', 'sort_order' => 144]);

        // Seed Colors
        Color::updateOrCreate(['color_code' => '00'], ['color_name' => 'Bianco', 'color_hex' => '#ffffff', 'sort_order' => 1]);
        Color::updateOrCreate(['color_code' => '01'], ['color_name' => 'Bianco Avorio', 'color_hex' => '#fffeef', 'sort_order' => 2]);
        Color::updateOrCreate(['color_code' => '02'], ['color_name' => 'Beige', 'color_hex' => '#CCCCCC', 'sort_order' => 3]);
        Color::updateOrCreate(['color_code' => '04'], ['color_name' => 'Khaki', 'color_hex' => '#c3b091', 'sort_order' => 4]);
        Color::updateOrCreate(['color_code' => '004'], ['color_name' => 'Colourblock', 'color_hex' => '#CCCCCC', 'sort_order' => 5]);
        Color::updateOrCreate(['color_code' => '07'], ['color_name' => 'Bianco Perla', 'color_hex' => '#eae6ca', 'sort_order' => 6]);
        Color::updateOrCreate(['color_code' => '10'], ['color_name' => 'Giallo Limone', 'color_hex' => '#c7b446', 'sort_order' => 7]);
        Color::updateOrCreate(['color_code' => '11'], ['color_name' => 'Giallo Hv', 'color_hex' => '#ffff00', 'sort_order' => 8]);
        Color::updateOrCreate(['color_code' => '17'], ['color_name' => 'Arancio/Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 9]);
        Color::updateOrCreate(['color_code' => '18'], ['color_name' => 'Arancio', 'color_hex' => '#ff9900', 'sort_order' => 10]);
        Color::updateOrCreate(['color_code' => '19'], ['color_name' => 'Arancio Bruciato', 'color_hex' => '#ff7514', 'sort_order' => 11]);
        Color::updateOrCreate(['color_code' => '21'], ['color_name' => 'Rosa', 'color_hex' => '#CCCCCC', 'sort_order' => 12]);
        Color::updateOrCreate(['color_code' => '34'], ['color_name' => 'Rosso', 'color_hex' => '#CCCCCC', 'sort_order' => 13]);
        Color::updateOrCreate(['color_code' => '35'], ['color_name' => 'Rosso', 'color_hex' => '#ff0000', 'sort_order' => 14]);
        Color::updateOrCreate(['color_code' => '0035'], ['color_name' => 'Bianco/Rosso', 'color_hex' => '#CCCCCC', 'sort_order' => 15]);
        Color::updateOrCreate(['color_code' => '38'], ['color_name' => 'Bordeaux', 'color_hex' => '#800000', 'sort_order' => 16]);
        Color::updateOrCreate(['color_code' => '44'], ['color_name' => 'Viola', 'color_hex' => '#8f00ff', 'sort_order' => 17]);
        Color::updateOrCreate(['color_code' => '51'], ['color_name' => 'Azzurro Cielo', 'color_hex' => '#CCCCCC', 'sort_order' => 18]);
        Color::updateOrCreate(['color_code' => '53'], ['color_name' => 'Blu Cielo', 'color_hex' => '#CCCCCC', 'sort_order' => 19]);
        Color::updateOrCreate(['color_code' => '54'], ['color_name' => 'Turchese', 'color_hex' => '#30d5c8', 'sort_order' => 20]);
        Color::updateOrCreate(['color_code' => '55'], ['color_name' => 'Royal', 'color_hex' => '#4169e1', 'sort_order' => 21]);
        Color::updateOrCreate(['color_code' => '56'], ['color_name' => 'Cobalto', 'color_hex' => '#0047ab', 'sort_order' => 22]);
        Color::updateOrCreate(['color_code' => '57'], ['color_name' => 'Azzurro', 'color_hex' => '#007fff', 'sort_order' => 23]);
        Color::updateOrCreate(['color_code' => '58'], ['color_name' => 'Blu Navy', 'color_hex' => '#000080', 'sort_order' => 24]);
        Color::updateOrCreate(['color_code' => '0058'], ['color_name' => 'Bianco/Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 25]);
        Color::updateOrCreate(['color_code' => '0062'], ['color_name' => 'Bianco/Verde Bandiera', 'color_hex' => '#CCCCCC', 'sort_order' => 26]);
        Color::updateOrCreate(['color_code' => '65'], ['color_name' => 'Green', 'color_hex' => '#CCCCCC', 'sort_order' => 27]);
        Color::updateOrCreate(['color_code' => '66'], ['color_name' => 'Verde Foresta', 'color_hex' => '#228b22', 'sort_order' => 28]);
        Color::updateOrCreate(['color_code' => '67'], ['color_name' => 'Verde Mela', 'color_hex' => '#66ff00', 'sort_order' => 29]);
        Color::updateOrCreate(['color_code' => '68'], ['color_name' => 'Verde Bottiglia', 'color_hex' => '#343b29', 'sort_order' => 30]);
        Color::updateOrCreate(['color_code' => '71'], ['color_name' => 'Verde Militare', 'color_hex' => '#556832', 'sort_order' => 31]);
        Color::updateOrCreate(['color_code' => '75'], ['color_name' => 'Verde Bamboo', 'color_hex' => '#40826d', 'sort_order' => 32]);
        Color::updateOrCreate(['color_code' => '82'], ['color_name' => 'Sabbia', 'color_hex' => '#f4a460', 'sort_order' => 33]);
        Color::updateOrCreate(['color_code' => '83'], ['color_name' => 'Pietra', 'color_hex' => '#CCCCCC', 'sort_order' => 34]);
        Color::updateOrCreate(['color_code' => '90'], ['color_name' => 'Grigio', 'color_hex' => '#808080', 'sort_order' => 35]);
        Color::updateOrCreate(['color_code' => '91'], ['color_name' => 'Pietra', 'color_hex' => '#8b8c7a', 'sort_order' => 36]);
        Color::updateOrCreate(['color_code' => '92'], ['color_name' => 'Grigio Cenere', 'color_hex' => '#e4e5e0', 'sort_order' => 37]);
        Color::updateOrCreate(['color_code' => '93'], ['color_name' => 'Grigio', 'color_hex' => '#CCCCCC', 'sort_order' => 38]);
        Color::updateOrCreate(['color_code' => '94'], ['color_name' => 'Grigio Argento', 'color_hex' => '#c0c0c0', 'sort_order' => 39]);
        Color::updateOrCreate(['color_code' => '95'], ['color_name' => 'Grigio Melange', 'color_hex' => '#b2b2b2', 'sort_order' => 40]);
        Color::updateOrCreate(['color_code' => '0095'], ['color_name' => 'White Print', 'color_hex' => '#CCCCCC', 'sort_order' => 41]);
        Color::updateOrCreate(['color_code' => '96'], ['color_name' => 'Canna Di Fucile', 'color_hex' => '#2f4f4f', 'sort_order' => 42]);
        Color::updateOrCreate(['color_code' => '98'], ['color_name' => 'Girgio', 'color_hex' => '#CCCCCC', 'sort_order' => 43]);
        Color::updateOrCreate(['color_code' => '99'], ['color_name' => 'Nero', 'color_hex' => '#000000', 'sort_order' => 44]);
        Color::updateOrCreate(['color_code' => '0099'], ['color_name' => 'Bianco/Nero', 'color_hex' => '#CCCCCC', 'sort_order' => 45]);
        Color::updateOrCreate(['color_code' => '100'], ['color_name' => 'White', 'color_hex' => '#CCCCCC', 'sort_order' => 46]);
        Color::updateOrCreate(['color_code' => '101'], ['color_name' => 'Giallo Hv', 'color_hex' => '#CCCCCC', 'sort_order' => 47]);
        Color::updateOrCreate(['color_code' => '111'], ['color_name' => 'Giallo Hv', 'color_hex' => '#CCCCCC', 'sort_order' => 48]);
        Color::updateOrCreate(['color_code' => '120'], ['color_name' => 'Grey Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 49]);
        Color::updateOrCreate(['color_code' => '121'], ['color_name' => 'Grigio Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 50]);
        Color::updateOrCreate(['color_code' => '131'], ['color_name' => 'Grigio Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 51]);
        Color::updateOrCreate(['color_code' => '133'], ['color_name' => 'Grigio Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 52]);
        Color::updateOrCreate(['color_code' => '134'], ['color_name' => 'Grigio Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 53]);
        Color::updateOrCreate(['color_code' => '135'], ['color_name' => 'Grigio Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 54]);
        Color::updateOrCreate(['color_code' => '137'], ['color_name' => 'Grigio', 'color_hex' => '#CCCCCC', 'sort_order' => 55]);
        Color::updateOrCreate(['color_code' => '138'], ['color_name' => 'Grigio Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 56]);
        Color::updateOrCreate(['color_code' => '140'], ['color_name' => 'Grey Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 57]);
        Color::updateOrCreate(['color_code' => '142'], ['color_name' => 'Grigio Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 58]);
        Color::updateOrCreate(['color_code' => '150'], ['color_name' => 'Sabbia', 'color_hex' => '#CCCCCC', 'sort_order' => 59]);
        Color::updateOrCreate(['color_code' => '170'], ['color_name' => 'Arancio Hv', 'color_hex' => '#ff2301', 'sort_order' => 60]);
        Color::updateOrCreate(['color_code' => '171'], ['color_name' => 'Arancio Neon', 'color_hex' => '#CCCCCC', 'sort_order' => 61]);
        Color::updateOrCreate(['color_code' => '173'], ['color_name' => 'Sabbia', 'color_hex' => '#CCCCCC', 'sort_order' => 62]);
        Color::updateOrCreate(['color_code' => '175'], ['color_name' => 'Arancione', 'color_hex' => '#ffa500', 'sort_order' => 63]);
        Color::updateOrCreate(['color_code' => '180'], ['color_name' => 'Khaki', 'color_hex' => '#CCCCCC', 'sort_order' => 64]);
        Color::updateOrCreate(['color_code' => '183'], ['color_name' => 'Beige Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 65]);
        Color::updateOrCreate(['color_code' => '190'], ['color_name' => 'Nocciola', 'color_hex' => '#CCCCCC', 'sort_order' => 66]);
        Color::updateOrCreate(['color_code' => '203'], ['color_name' => 'Rosa Antico', 'color_hex' => '#d36e70', 'sort_order' => 67]);
        Color::updateOrCreate(['color_code' => '208'], ['color_name' => 'Giallo Limone', 'color_hex' => '#CCCCCC', 'sort_order' => 68]);
        Color::updateOrCreate(['color_code' => '210'], ['color_name' => 'Pink Mist', 'color_hex' => '#CCCCCC', 'sort_order' => 69]);
        Color::updateOrCreate(['color_code' => '211'], ['color_name' => 'Rosa Neon', 'color_hex' => '#CCCCCC', 'sort_order' => 70]);
        Color::updateOrCreate(['color_code' => '212'], ['color_name' => 'Giallo', 'color_hex' => '#CCCCCC', 'sort_order' => 71]);
        Color::updateOrCreate(['color_code' => '215'], ['color_name' => 'Rosa Confetto', 'color_hex' => '#fadadd', 'sort_order' => 72]);
        Color::updateOrCreate(['color_code' => '216'], ['color_name' => 'Erica', 'color_hex' => '#CCCCCC', 'sort_order' => 73]);
        Color::updateOrCreate(['color_code' => '220'], ['color_name' => 'Giallo', 'color_hex' => '#CCCCCC', 'sort_order' => 74]);
        Color::updateOrCreate(['color_code' => '222'], ['color_name' => 'Giallo Neon', 'color_hex' => '#CCCCCC', 'sort_order' => 75]);
        Color::updateOrCreate(['color_code' => '250'], ['color_name' => 'Rosa Brillante', 'color_hex' => '#ff007f', 'sort_order' => 76]);
        Color::updateOrCreate(['color_code' => '252'], ['color_name' => 'Ocra', 'color_hex' => '#CCCCCC', 'sort_order' => 77]);
        Color::updateOrCreate(['color_code' => '260'], ['color_name' => 'Neon Cerise', 'color_hex' => '#CCCCCC', 'sort_order' => 78]);
        Color::updateOrCreate(['color_code' => '300'], ['color_name' => 'Lampone', 'color_hex' => '#e30b5c', 'sort_order' => 79]);
        Color::updateOrCreate(['color_code' => '305'], ['color_name' => 'Arancio', 'color_hex' => '#CCCCCC', 'sort_order' => 80]);
        Color::updateOrCreate(['color_code' => '307'], ['color_name' => 'Arancio', 'color_hex' => '#CCCCCC', 'sort_order' => 81]);
        Color::updateOrCreate(['color_code' => '308'], ['color_name' => 'Arancio', 'color_hex' => '#CCCCCC', 'sort_order' => 82]);
        Color::updateOrCreate(['color_code' => '320'], ['color_name' => 'Arancio', 'color_hex' => '#CCCCCC', 'sort_order' => 83]);
        Color::updateOrCreate(['color_code' => '340'], ['color_name' => 'Peach', 'color_hex' => '#CCCCCC', 'sort_order' => 84]);
        Color::updateOrCreate(['color_code' => '365'], ['color_name' => 'Red Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 85]);
        Color::updateOrCreate(['color_code' => '382'], ['color_name' => 'Bordeaux', 'color_hex' => '#CCCCCC', 'sort_order' => 86]);
        Color::updateOrCreate(['color_code' => '400'], ['color_name' => 'Red', 'color_hex' => '#CCCCCC', 'sort_order' => 87]);
        Color::updateOrCreate(['color_code' => '406'], ['color_name' => 'Rosso Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 88]);
        Color::updateOrCreate(['color_code' => '407'], ['color_name' => 'Burgundy', 'color_hex' => '#CCCCCC', 'sort_order' => 89]);
        Color::updateOrCreate(['color_code' => '440'], ['color_name' => 'Viola', 'color_hex' => '#CCCCCC', 'sort_order' => 90]);
        Color::updateOrCreate(['color_code' => '471'], ['color_name' => 'Rosa Chiaro', 'color_hex' => '#CCCCCC', 'sort_order' => 91]);
        Color::updateOrCreate(['color_code' => '474'], ['color_name' => 'Rosa Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 92]);
        Color::updateOrCreate(['color_code' => '481'], ['color_name' => 'Bordeaux', 'color_hex' => '#CCCCCC', 'sort_order' => 93]);
        Color::updateOrCreate(['color_code' => '484'], ['color_name' => 'Rosso Mattone', 'color_hex' => '#CCCCCC', 'sort_order' => 94]);
        Color::updateOrCreate(['color_code' => '486'], ['color_name' => 'Bordeaux', 'color_hex' => '#CCCCCC', 'sort_order' => 95]);
        Color::updateOrCreate(['color_code' => '488'], ['color_name' => 'Bordeaux', 'color_hex' => '#CCCCCC', 'sort_order' => 96]);
        Color::updateOrCreate(['color_code' => '500'], ['color_name' => 'Light Blue', 'color_hex' => '#CCCCCC', 'sort_order' => 97]);
        Color::updateOrCreate(['color_code' => '501'], ['color_name' => 'Azzurro Cielo', 'color_hex' => '#CCCCCC', 'sort_order' => 98]);
        Color::updateOrCreate(['color_code' => '503'], ['color_name' => 'Azzurro', 'color_hex' => '#CCCCCC', 'sort_order' => 99]);
        Color::updateOrCreate(['color_code' => '505'], ['color_name' => 'French Blue', 'color_hex' => '#CCCCCC', 'sort_order' => 100]);
        Color::updateOrCreate(['color_code' => '506'], ['color_name' => 'Azzurro Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 101]);
        Color::updateOrCreate(['color_code' => '509'], ['color_name' => 'Light Blue', 'color_hex' => '#CCCCCC', 'sort_order' => 102]);
        Color::updateOrCreate(['color_code' => '510'], ['color_name' => 'Azzurro Brillante', 'color_hex' => '#CCCCCC', 'sort_order' => 103]);
        Color::updateOrCreate(['color_code' => '511'], ['color_name' => 'Azzurro Neon', 'color_hex' => '#CCCCCC', 'sort_order' => 104]);
        Color::updateOrCreate(['color_code' => '512'], ['color_name' => 'Dream Blue', 'color_hex' => '#CCCCCC', 'sort_order' => 105]);
        Color::updateOrCreate(['color_code' => '513'], ['color_name' => 'Azzurro Cielo', 'color_hex' => '#CCCCCC', 'sort_order' => 106]);
        Color::updateOrCreate(['color_code' => '514'], ['color_name' => 'Azzurro Polvere', 'color_hex' => '#CCCCCC', 'sort_order' => 107]);
        Color::updateOrCreate(['color_code' => '516'], ['color_name' => 'Turchese', 'color_hex' => '#CCCCCC', 'sort_order' => 108]);
        Color::updateOrCreate(['color_code' => '523'], ['color_name' => 'Petrolio', 'color_hex' => '#CCCCCC', 'sort_order' => 109]);
        Color::updateOrCreate(['color_code' => '530'], ['color_name' => 'Blu', 'color_hex' => '#CCCCCC', 'sort_order' => 110]);
        Color::updateOrCreate(['color_code' => '533'], ['color_name' => 'Blu/Bianco', 'color_hex' => '#CCCCCC', 'sort_order' => 111]);
        Color::updateOrCreate(['color_code' => '534'], ['color_name' => 'Blue', 'color_hex' => '#CCCCCC', 'sort_order' => 112]);
        Color::updateOrCreate(['color_code' => '535'], ['color_name' => 'Cobalt Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 113]);
        Color::updateOrCreate(['color_code' => '542'], ['color_name' => 'Blu Elettrico', 'color_hex' => '#CCCCCC', 'sort_order' => 114]);
        Color::updateOrCreate(['color_code' => '554'], ['color_name' => 'Navy Mélange', 'color_hex' => '#000080', 'sort_order' => 115]);
        Color::updateOrCreate(['color_code' => '555'], ['color_name' => 'Blu', 'color_hex' => '#CCCCCC', 'sort_order' => 116]);
        Color::updateOrCreate(['color_code' => '556'], ['color_name' => 'Blu', 'color_hex' => '#CCCCCC', 'sort_order' => 117]);
        Color::updateOrCreate(['color_code' => '558'], ['color_name' => 'Dark Indigo', 'color_hex' => '#CCCCCC', 'sort_order' => 118]);
        Color::updateOrCreate(['color_code' => '565'], ['color_name' => 'Blu Melange', 'color_hex' => '#5f9ea0', 'sort_order' => 119]);
        Color::updateOrCreate(['color_code' => '569'], ['color_name' => 'Denim Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 120]);
        Color::updateOrCreate(['color_code' => '570'], ['color_name' => 'Azzurro Pastello', 'color_hex' => '#afeeee', 'sort_order' => 121]);
        Color::updateOrCreate(['color_code' => '575'], ['color_name' => 'Blu Nebbia', 'color_hex' => '#778899', 'sort_order' => 122]);
        Color::updateOrCreate(['color_code' => '578'], ['color_name' => 'Cobolt Blue', 'color_hex' => '#CCCCCC', 'sort_order' => 123]);
        Color::updateOrCreate(['color_code' => '580'], ['color_name' => 'Blu', 'color_hex' => '#00008b', 'sort_order' => 124]);
        Color::updateOrCreate(['color_code' => '581'], ['color_name' => 'Denim', 'color_hex' => '#1560bd', 'sort_order' => 125]);
        Color::updateOrCreate(['color_code' => '585'], ['color_name' => 'Blu Bandiera', 'color_hex' => '#CCCCCC', 'sort_order' => 126]);
        Color::updateOrCreate(['color_code' => '586'], ['color_name' => 'Antracit Blue Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 127]);
        Color::updateOrCreate(['color_code' => '591'], ['color_name' => 'Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 128]);
        Color::updateOrCreate(['color_code' => '592'], ['color_name' => 'Navy Denim', 'color_hex' => '#CCCCCC', 'sort_order' => 129]);
        Color::updateOrCreate(['color_code' => '593'], ['color_name' => 'Blu Polare', 'color_hex' => '#CCCCCC', 'sort_order' => 130]);
        Color::updateOrCreate(['color_code' => '595'], ['color_name' => 'Blu Acciaio', 'color_hex' => '#4682b4', 'sort_order' => 131]);
        Color::updateOrCreate(['color_code' => '597'], ['color_name' => 'Sea Blue Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 132]);
        Color::updateOrCreate(['color_code' => '599'], ['color_name' => 'Laguna', 'color_hex' => '#CCCCCC', 'sort_order' => 133]);
        Color::updateOrCreate(['color_code' => '600'], ['color_name' => 'Verde Lime', 'color_hex' => '#ccff00', 'sort_order' => 134]);
        Color::updateOrCreate(['color_code' => '601'], ['color_name' => 'Navy Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 135]);
        Color::updateOrCreate(['color_code' => '603'], ['color_name' => 'Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 136]);
        Color::updateOrCreate(['color_code' => '605'], ['color_name' => 'Verde Acido', 'color_hex' => '#7fff00', 'sort_order' => 137]);
        Color::updateOrCreate(['color_code' => '606'], ['color_name' => 'Blu Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 138]);
        Color::updateOrCreate(['color_code' => '607'], ['color_name' => 'Navy Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 139]);
        Color::updateOrCreate(['color_code' => '608'], ['color_name' => 'Verde Lime', 'color_hex' => '#CCCCCC', 'sort_order' => 140]);
        Color::updateOrCreate(['color_code' => '609'], ['color_name' => 'Blu Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 141]);
        Color::updateOrCreate(['color_code' => '611'], ['color_name' => 'Verde Neon', 'color_hex' => '#CCCCCC', 'sort_order' => 142]);
        Color::updateOrCreate(['color_code' => '613'], ['color_name' => 'Navy/Bianco', 'color_hex' => '#CCCCCC', 'sort_order' => 143]);
        Color::updateOrCreate(['color_code' => '615'], ['color_name' => 'Verde Salvia', 'color_hex' => '#9dc183', 'sort_order' => 144]);
        Color::updateOrCreate(['color_code' => '616'], ['color_name' => 'Dark Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 145]);
        Color::updateOrCreate(['color_code' => '622'], ['color_name' => 'Petrolio', 'color_hex' => '#CCCCCC', 'sort_order' => 146]);
        Color::updateOrCreate(['color_code' => '625'], ['color_name' => 'Petrolio Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 147]);
        Color::updateOrCreate(['color_code' => '630'], ['color_name' => 'Olive Green', 'color_hex' => '#CCCCCC', 'sort_order' => 148]);
        Color::updateOrCreate(['color_code' => '631'], ['color_name' => 'Blu Artico', 'color_hex' => '#CCCCCC', 'sort_order' => 149]);
        Color::updateOrCreate(['color_code' => '632'], ['color_name' => 'Oceanblue', 'color_hex' => '#CCCCCC', 'sort_order' => 150]);
        Color::updateOrCreate(['color_code' => '640'], ['color_name' => 'Verde Militare', 'color_hex' => '#CCCCCC', 'sort_order' => 151]);
        Color::updateOrCreate(['color_code' => '668'], ['color_name' => 'Azzurro', 'color_hex' => '#CCCCCC', 'sort_order' => 152]);
        Color::updateOrCreate(['color_code' => '676'], ['color_name' => 'Verde Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 153]);
        Color::updateOrCreate(['color_code' => '677'], ['color_name' => 'Green', 'color_hex' => '#CCCCCC', 'sort_order' => 154]);
        Color::updateOrCreate(['color_code' => '692'], ['color_name' => 'Dark Denim', 'color_hex' => '#CCCCCC', 'sort_order' => 155]);
        Color::updateOrCreate(['color_code' => '694'], ['color_name' => 'Verde Bosco', 'color_hex' => '#CCCCCC', 'sort_order' => 156]);
        Color::updateOrCreate(['color_code' => '704'], ['color_name' => 'Verde Militare', 'color_hex' => '#CCCCCC', 'sort_order' => 157]);
        Color::updateOrCreate(['color_code' => '707'], ['color_name' => 'Verde Bottiglia', 'color_hex' => '#CCCCCC', 'sort_order' => 158]);
        Color::updateOrCreate(['color_code' => '720'], ['color_name' => 'Pine Green', 'color_hex' => '#CCCCCC', 'sort_order' => 159]);
        Color::updateOrCreate(['color_code' => '722'], ['color_name' => 'Verde Bosco', 'color_hex' => '#CCCCCC', 'sort_order' => 160]);
        Color::updateOrCreate(['color_code' => '728'], ['color_name' => 'Fresh Green', 'color_hex' => '#CCCCCC', 'sort_order' => 161]);
        Color::updateOrCreate(['color_code' => '729'], ['color_name' => 'Verde', 'color_hex' => '#CCCCCC', 'sort_order' => 162]);
        Color::updateOrCreate(['color_code' => '730'], ['color_name' => 'Lime', 'color_hex' => '#CCCCCC', 'sort_order' => 163]);
        Color::updateOrCreate(['color_code' => '784'], ['color_name' => 'Verde Acqua', 'color_hex' => '#CCCCCC', 'sort_order' => 164]);
        Color::updateOrCreate(['color_code' => '802'], ['color_name' => 'Cammello', 'color_hex' => '#CCCCCC', 'sort_order' => 165]);
        Color::updateOrCreate(['color_code' => '805'], ['color_name' => 'Cognac', 'color_hex' => '#CCCCCC', 'sort_order' => 166]);
        Color::updateOrCreate(['color_code' => '810'], ['color_name' => 'Sand Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 167]);
        Color::updateOrCreate(['color_code' => '815'], ['color_name' => 'Beige', 'color_hex' => '#f5f5dc', 'sort_order' => 168]);
        Color::updateOrCreate(['color_code' => '816'], ['color_name' => 'Ecru', 'color_hex' => '#CCCCCC', 'sort_order' => 169]);
        Color::updateOrCreate(['color_code' => '820'], ['color_name' => 'Caffe Latte', 'color_hex' => '#d2691e', 'sort_order' => 170]);
        Color::updateOrCreate(['color_code' => '825'], ['color_name' => 'Marrone Moka', 'color_hex' => '#8a5a3a', 'sort_order' => 171]);
        Color::updateOrCreate(['color_code' => '834'], ['color_name' => 'Nocciola Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 172]);
        Color::updateOrCreate(['color_code' => '836'], ['color_name' => 'Brown Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 173]);
        Color::updateOrCreate(['color_code' => '900'], ['color_name' => 'Black', 'color_hex' => '#CCCCCC', 'sort_order' => 174]);
        Color::updateOrCreate(['color_code' => '901'], ['color_name' => 'Nero Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 175]);
        Color::updateOrCreate(['color_code' => '903'], ['color_name' => 'Nero/Bianco', 'color_hex' => '#CCCCCC', 'sort_order' => 176]);
        Color::updateOrCreate(['color_code' => '906'], ['color_name' => 'Nero Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 177]);
        Color::updateOrCreate(['color_code' => '907'], ['color_name' => 'Antracite Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 178]);
        Color::updateOrCreate(['color_code' => '909'], ['color_name' => 'Antracite Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 179]);
        Color::updateOrCreate(['color_code' => '913'], ['color_name' => 'Grigio/Bianco', 'color_hex' => '#CCCCCC', 'sort_order' => 180]);
        Color::updateOrCreate(['color_code' => '914'], ['color_name' => 'Antracite', 'color_hex' => '#CCCCCC', 'sort_order' => 181]);
        Color::updateOrCreate(['color_code' => '919'], ['color_name' => 'Antracite', 'color_hex' => '#CCCCCC', 'sort_order' => 182]);
        Color::updateOrCreate(['color_code' => '920'], ['color_name' => 'Denim Grey', 'color_hex' => '#CCCCCC', 'sort_order' => 183]);
        Color::updateOrCreate(['color_code' => '921'], ['color_name' => 'Grey', 'color_hex' => '#CCCCCC', 'sort_order' => 184]);
        Color::updateOrCreate(['color_code' => '925'], ['color_name' => 'Nature Melange', 'color_hex' => '#b5b8b1', 'sort_order' => 185]);
        Color::updateOrCreate(['color_code' => '934'], ['color_name' => 'Steel Grey', 'color_hex' => '#CCCCCC', 'sort_order' => 186]);
        Color::updateOrCreate(['color_code' => '935'], ['color_name' => 'Steel Grey', 'color_hex' => '#CCCCCC', 'sort_order' => 187]);
        Color::updateOrCreate(['color_code' => '936'], ['color_name' => 'Grigio', 'color_hex' => '#CCCCCC', 'sort_order' => 188]);
        Color::updateOrCreate(['color_code' => '945'], ['color_name' => 'Grigio Fumo', 'color_hex' => '#e5e5e5', 'sort_order' => 189]);
        Color::updateOrCreate(['color_code' => '947'], ['color_name' => 'Rifrangente', 'color_hex' => '#f4f4f4', 'sort_order' => 190]);
        Color::updateOrCreate(['color_code' => '949'], ['color_name' => 'Rifrangente Chiaro', 'color_hex' => '#f6f6f6', 'sort_order' => 191]);
        Color::updateOrCreate(['color_code' => '950'], ['color_name' => 'Grigio Metallo', 'color_hex' => '#CCCCCC', 'sort_order' => 192]);
        Color::updateOrCreate(['color_code' => '955'], ['color_name' => 'Antracite Melange', 'color_hex' => '#293133', 'sort_order' => 193]);
        Color::updateOrCreate(['color_code' => '956'], ['color_name' => 'Grigio Metallo', 'color_hex' => '#a8a9ad', 'sort_order' => 194]);
        Color::updateOrCreate(['color_code' => '992'], ['color_name' => 'Nero Denim', 'color_hex' => '#CCCCCC', 'sort_order' => 195]);
        Color::updateOrCreate(['color_code' => '999'], ['color_name' => 'Nero/Nero', 'color_hex' => '#CCCCCC', 'sort_order' => 196]);
        Color::updateOrCreate(['color_code' => '1341'], ['color_name' => 'Mff Blue', 'color_hex' => '#CCCCCC', 'sort_order' => 197]);
        Color::updateOrCreate(['color_code' => '1345'], ['color_name' => 'Royal Blue', 'color_hex' => '#CCCCCC', 'sort_order' => 198]);
        Color::updateOrCreate(['color_code' => '1346'], ['color_name' => 'Club Cobolt', 'color_hex' => '#CCCCCC', 'sort_order' => 199]);
        Color::updateOrCreate(['color_code' => '1390'], ['color_name' => 'Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 200]);
        Color::updateOrCreate(['color_code' => '1395'], ['color_name' => 'Dk Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 201]);
        Color::updateOrCreate(['color_code' => '1430'], ['color_name' => 'Bright Red', 'color_hex' => '#CCCCCC', 'sort_order' => 202]);
        Color::updateOrCreate(['color_code' => '1471'], ['color_name' => 'Pop', 'color_hex' => '#CCCCCC', 'sort_order' => 203]);
        Color::updateOrCreate(['color_code' => '1474'], ['color_name' => 'Metro', 'color_hex' => '#CCCCCC', 'sort_order' => 204]);
        Color::updateOrCreate(['color_code' => '1552'], ['color_name' => 'Sweden Yellow', 'color_hex' => '#CCCCCC', 'sort_order' => 205]);
        Color::updateOrCreate(['color_code' => '1570'], ['color_name' => 'Cocktail', 'color_hex' => '#CCCCCC', 'sort_order' => 206]);
        Color::updateOrCreate(['color_code' => '1606'], ['color_name' => 'Craft Green', 'color_hex' => '#CCCCCC', 'sort_order' => 207]);
        Color::updateOrCreate(['color_code' => '1651'], ['color_name' => 'Team Green', 'color_hex' => '#CCCCCC', 'sort_order' => 208]);
        Color::updateOrCreate(['color_code' => '1777'], ['color_name' => 'Maroon', 'color_hex' => '#CCCCCC', 'sort_order' => 209]);
        Color::updateOrCreate(['color_code' => '1799'], ['color_name' => 'Arancio/Nero', 'color_hex' => '#CCCCCC', 'sort_order' => 210]);
        Color::updateOrCreate(['color_code' => '1850'], ['color_name' => 'Neon', 'color_hex' => '#CCCCCC', 'sort_order' => 211]);
        Color::updateOrCreate(['color_code' => '1851'], ['color_name' => 'Flumino', 'color_hex' => '#CCCCCC', 'sort_order' => 212]);
        Color::updateOrCreate(['color_code' => '1900'], ['color_name' => 'White', 'color_hex' => '#CCCCCC', 'sort_order' => 213]);
        Color::updateOrCreate(['color_code' => '1975'], ['color_name' => 'Dk Grey Melange/Black', 'color_hex' => '#CCCCCC', 'sort_order' => 214]);
        Color::updateOrCreate(['color_code' => '1999'], ['color_name' => 'Black', 'color_hex' => '#CCCCCC', 'sort_order' => 215]);
        Color::updateOrCreate(['color_code' => '2345'], ['color_name' => 'Royal Blue/Sweden Yellow', 'color_hex' => '#CCCCCC', 'sort_order' => 216]);
        Color::updateOrCreate(['color_code' => '2346'], ['color_name' => 'Club Cobolt/Sweden Yellow', 'color_hex' => '#CCCCCC', 'sort_order' => 217]);
        Color::updateOrCreate(['color_code' => '2430'], ['color_name' => 'Bright Red/Black', 'color_hex' => '#CCCCCC', 'sort_order' => 218]);
        Color::updateOrCreate(['color_code' => '2552'], ['color_name' => 'Sweden Yellow/Royal Blue', 'color_hex' => '#CCCCCC', 'sort_order' => 219]);
        Color::updateOrCreate(['color_code' => '2851'], ['color_name' => 'Flumino/Black', 'color_hex' => '#CCCCCC', 'sort_order' => 220]);
        Color::updateOrCreate(['color_code' => '2900'], ['color_name' => 'White/Royal', 'color_hex' => '#CCCCCC', 'sort_order' => 221]);
        Color::updateOrCreate(['color_code' => '3346'], ['color_name' => 'Club Cobolt/Bright Red', 'color_hex' => '#CCCCCC', 'sort_order' => 222]);
        Color::updateOrCreate(['color_code' => '3500'], ['color_name' => 'Rosso/Bianco', 'color_hex' => '#CCCCCC', 'sort_order' => 223]);
        Color::updateOrCreate(['color_code' => '3535'], ['color_name' => 'Red Print', 'color_hex' => '#CCCCCC', 'sort_order' => 224]);
        Color::updateOrCreate(['color_code' => '3552'], ['color_name' => 'Sweden Yellow/Club Cobolt', 'color_hex' => '#CCCCCC', 'sort_order' => 225]);
        Color::updateOrCreate(['color_code' => '3562'], ['color_name' => 'Rosso/Verde Bandiera', 'color_hex' => '#CCCCCC', 'sort_order' => 226]);
        Color::updateOrCreate(['color_code' => '3800'], ['color_name' => 'Burgundy/White', 'color_hex' => '#CCCCCC', 'sort_order' => 227]);
        Color::updateOrCreate(['color_code' => '3900'], ['color_name' => 'White/Team Green', 'color_hex' => '#CCCCCC', 'sort_order' => 228]);
        Color::updateOrCreate(['color_code' => '4900'], ['color_name' => 'White/Bright Red', 'color_hex' => '#CCCCCC', 'sort_order' => 229]);
        Color::updateOrCreate(['color_code' => '5360'], ['color_name' => 'Blu/Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 230]);
        Color::updateOrCreate(['color_code' => '5500'], ['color_name' => 'Royal Blu/Bianco', 'color_hex' => '#CCCCCC', 'sort_order' => 231]);
        Color::updateOrCreate(['color_code' => '5562'], ['color_name' => 'Royal/Verde Bandiera', 'color_hex' => '#CCCCCC', 'sort_order' => 232]);
        Color::updateOrCreate(['color_code' => '5800'], ['color_name' => 'Navy/Bianco', 'color_hex' => '#CCCCCC', 'sort_order' => 233]);
        Color::updateOrCreate(['color_code' => '5810'], ['color_name' => 'Navy/Giallo', 'color_hex' => '#CCCCCC', 'sort_order' => 234]);
        Color::updateOrCreate(['color_code' => '5900'], ['color_name' => 'White/Club Cobolt', 'color_hex' => '#CCCCCC', 'sort_order' => 235]);
        Color::updateOrCreate(['color_code' => '6021'], ['color_name' => 'Navy/Neon Yellow', 'color_hex' => '#CCCCCC', 'sort_order' => 236]);
        Color::updateOrCreate(['color_code' => '6031'], ['color_name' => 'Navy/Neon Orange', 'color_hex' => '#CCCCCC', 'sort_order' => 237]);
        Color::updateOrCreate(['color_code' => '6053'], ['color_name' => 'Navy/Blu', 'color_hex' => '#CCCCCC', 'sort_order' => 238]);
        Color::updateOrCreate(['color_code' => '6200'], ['color_name' => 'Verde Bandiera/Bianco', 'color_hex' => '#CCCCCC', 'sort_order' => 239]);
        Color::updateOrCreate(['color_code' => '007999'], ['color_name' => 'Multi-Black', 'color_hex' => '#CCCCCC', 'sort_order' => 240]);
        Color::updateOrCreate(['color_code' => '9030'], ['color_name' => 'Nero/Arancio', 'color_hex' => '#CCCCCC', 'sort_order' => 241]);
        Color::updateOrCreate(['color_code' => '9040'], ['color_name' => 'Nero/Rosso', 'color_hex' => '#CCCCCC', 'sort_order' => 242]);
        Color::updateOrCreate(['color_code' => '9093'], ['color_name' => 'Nero/Antracite', 'color_hex' => '#CCCCCC', 'sort_order' => 243]);
        Color::updateOrCreate(['color_code' => '9345'], ['color_name' => 'Black/Royal Blue', 'color_hex' => '#CCCCCC', 'sort_order' => 244]);
        Color::updateOrCreate(['color_code' => '9346'], ['color_name' => 'Black/Club Cobolt', 'color_hex' => '#CCCCCC', 'sort_order' => 245]);
        Color::updateOrCreate(['color_code' => '9390'], ['color_name' => 'Antracite/Nero', 'color_hex' => '#CCCCCC', 'sort_order' => 246]);
        Color::updateOrCreate(['color_code' => '9430'], ['color_name' => 'Black/Bright Red', 'color_hex' => '#CCCCCC', 'sort_order' => 247]);
        Color::updateOrCreate(['color_code' => '9471'], ['color_name' => 'Black/Pop', 'color_hex' => '#CCCCCC', 'sort_order' => 248]);
        Color::updateOrCreate(['color_code' => '9552'], ['color_name' => 'Black/Sweden Yellow', 'color_hex' => '#CCCCCC', 'sort_order' => 249]);
        Color::updateOrCreate(['color_code' => '9651'], ['color_name' => 'Black/Team Green', 'color_hex' => '#CCCCCC', 'sort_order' => 250]);
        Color::updateOrCreate(['color_code' => '9900'], ['color_name' => 'Black/White', 'color_hex' => '#CCCCCC', 'sort_order' => 251]);
        Color::updateOrCreate(['color_code' => '9910'], ['color_name' => 'Nero/Giallo', 'color_hex' => '#CCCCCC', 'sort_order' => 252]);
        Color::updateOrCreate(['color_code' => '9917'], ['color_name' => 'Nero/Arancio', 'color_hex' => '#CCCCCC', 'sort_order' => 253]);
        Color::updateOrCreate(['color_code' => '9935'], ['color_name' => 'Nero/Rosso', 'color_hex' => '#CCCCCC', 'sort_order' => 254]);
        Color::updateOrCreate(['color_code' => '9990'], ['color_name' => 'Black', 'color_hex' => '#CCCCCC', 'sort_order' => 255]);
        Color::updateOrCreate(['color_code' => '9993'], ['color_name' => 'Black/Light Grey', 'color_hex' => '#CCCCCC', 'sort_order' => 256]);
        Color::updateOrCreate(['color_code' => '9995'], ['color_name' => 'Bl.w.print', 'color_hex' => '#CCCCCC', 'sort_order' => 257]);
        Color::updateOrCreate(['color_code' => '9999'], ['color_name' => 'Black', 'color_hex' => '#CCCCCC', 'sort_order' => 258]);
        Color::updateOrCreate(['color_code' => '21000'], ['color_name' => 'Pink/White', 'color_hex' => '#CCCCCC', 'sort_order' => 259]);
        Color::updateOrCreate(['color_code' => '38580'], ['color_name' => 'Burgundy', 'color_hex' => '#CCCCCC', 'sort_order' => 260]);
        Color::updateOrCreate(['color_code' => '50500'], ['color_name' => 'French Blue/White Stripe', 'color_hex' => '#CCCCCC', 'sort_order' => 261]);
        Color::updateOrCreate(['color_code' => '58000'], ['color_name' => 'Dark Navy/White', 'color_hex' => '#CCCCCC', 'sort_order' => 262]);
        Color::updateOrCreate(['color_code' => '58035'], ['color_name' => 'Dark Navy/Red', 'color_hex' => '#CCCCCC', 'sort_order' => 263]);
        Color::updateOrCreate(['color_code' => '58055'], ['color_name' => 'Dark Navy/Royal', 'color_hex' => '#CCCCCC', 'sort_order' => 264]);
        Color::updateOrCreate(['color_code' => '58057'], ['color_name' => 'Dark Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 265]);
        Color::updateOrCreate(['color_code' => '58062'], ['color_name' => 'Blu/Verde Bandiera', 'color_hex' => '#CCCCCC', 'sort_order' => 266]);
        Color::updateOrCreate(['color_code' => '300000'], ['color_name' => 'Saphire', 'color_hex' => '#CCCCCC', 'sort_order' => 267]);
        Color::updateOrCreate(['color_code' => '300909'], ['color_name' => 'Saphire-Sulfur', 'color_hex' => '#CCCCCC', 'sort_order' => 268]);
        Color::updateOrCreate(['color_code' => '318000'], ['color_name' => 'Azure', 'color_hex' => '#CCCCCC', 'sort_order' => 269]);
        Color::updateOrCreate(['color_code' => '319000'], ['color_name' => 'Area', 'color_hex' => '#CCCCCC', 'sort_order' => 270]);
        Color::updateOrCreate(['color_code' => '319396'], ['color_name' => 'Area-Blaze', 'color_hex' => '#CCCCCC', 'sort_order' => 271]);
        Color::updateOrCreate(['color_code' => '333000'], ['color_name' => 'Menthol', 'color_hex' => '#CCCCCC', 'sort_order' => 272]);
        Color::updateOrCreate(['color_code' => '336000'], ['color_name' => 'Sweden Blue', 'color_hex' => '#CCCCCC', 'sort_order' => 273]);
        Color::updateOrCreate(['color_code' => '341900'], ['color_name' => 'Mff Blue/White', 'color_hex' => '#CCCCCC', 'sort_order' => 274]);
        Color::updateOrCreate(['color_code' => '345000'], ['color_name' => 'Royal', 'color_hex' => '#CCCCCC', 'sort_order' => 275]);
        Color::updateOrCreate(['color_code' => '345900'], ['color_name' => 'Royal/White', 'color_hex' => '#CCCCCC', 'sort_order' => 276]);
        Color::updateOrCreate(['color_code' => '346000'], ['color_name' => 'Club Cobolt', 'color_hex' => '#CCCCCC', 'sort_order' => 277]);
        Color::updateOrCreate(['color_code' => '346390'], ['color_name' => 'Club Cobolt/Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 278]);
        Color::updateOrCreate(['color_code' => '346430'], ['color_name' => 'Club Cobolt/Bright Red', 'color_hex' => '#CCCCCC', 'sort_order' => 279]);
        Color::updateOrCreate(['color_code' => '346900'], ['color_name' => 'Club Cobolt/White', 'color_hex' => '#CCCCCC', 'sort_order' => 280]);
        Color::updateOrCreate(['color_code' => '346999'], ['color_name' => 'Club Cobolt/Black', 'color_hex' => '#CCCCCC', 'sort_order' => 281]);
        Color::updateOrCreate(['color_code' => '349000'], ['color_name' => 'Beat', 'color_hex' => '#CCCCCC', 'sort_order' => 282]);
        Color::updateOrCreate(['color_code' => '349396'], ['color_name' => 'Beat-Blaze', 'color_hex' => '#CCCCCC', 'sort_order' => 283]);
        Color::updateOrCreate(['color_code' => '349645'], ['color_name' => 'Beat-Scream', 'color_hex' => '#CCCCCC', 'sort_order' => 284]);
        Color::updateOrCreate(['color_code' => '349985'], ['color_name' => 'Beat-Granite', 'color_hex' => '#CCCCCC', 'sort_order' => 285]);
        Color::updateOrCreate(['color_code' => '360000'], ['color_name' => 'Burst', 'color_hex' => '#CCCCCC', 'sort_order' => 286]);
        Color::updateOrCreate(['color_code' => '360396'], ['color_name' => 'Burst-Blaze', 'color_hex' => '#CCCCCC', 'sort_order' => 287]);
        Color::updateOrCreate(['color_code' => '390000'], ['color_name' => 'Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 288]);
        Color::updateOrCreate(['color_code' => '390346'], ['color_name' => 'Navy/Club Cobolt', 'color_hex' => '#CCCCCC', 'sort_order' => 289]);
        Color::updateOrCreate(['color_code' => '390390'], ['color_name' => 'Navy/Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 290]);
        Color::updateOrCreate(['color_code' => '390430'], ['color_name' => 'Navy/Bright Red', 'color_hex' => '#CCCCCC', 'sort_order' => 291]);
        Color::updateOrCreate(['color_code' => '390552'], ['color_name' => 'Navy/Sweden Yellow', 'color_hex' => '#CCCCCC', 'sort_order' => 292]);
        Color::updateOrCreate(['color_code' => '390900'], ['color_name' => 'Navy/White', 'color_hex' => '#CCCCCC', 'sort_order' => 293]);
        Color::updateOrCreate(['color_code' => '395000'], ['color_name' => 'Dark Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 294]);
        Color::updateOrCreate(['color_code' => '395200'], ['color_name' => 'Dark Navy Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 295]);
        Color::updateOrCreate(['color_code' => '396000'], ['color_name' => 'Blaze', 'color_hex' => '#CCCCCC', 'sort_order' => 296]);
        Color::updateOrCreate(['color_code' => '396200'], ['color_name' => 'Blaze Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 297]);
        Color::updateOrCreate(['color_code' => '396319'], ['color_name' => 'Blaze-Area', 'color_hex' => '#CCCCCC', 'sort_order' => 298]);
        Color::updateOrCreate(['color_code' => '396342'], ['color_name' => 'Blaze-Atmos', 'color_hex' => '#CCCCCC', 'sort_order' => 299]);
        Color::updateOrCreate(['color_code' => '396360'], ['color_name' => 'Blaze-Burst', 'color_hex' => '#CCCCCC', 'sort_order' => 300]);
        Color::updateOrCreate(['color_code' => '396404'], ['color_name' => 'Blaze-Lychee', 'color_hex' => '#CCCCCC', 'sort_order' => 301]);
        Color::updateOrCreate(['color_code' => '396676'], ['color_name' => 'Blaze-Universe', 'color_hex' => '#CCCCCC', 'sort_order' => 302]);
        Color::updateOrCreate(['color_code' => '404000'], ['color_name' => 'Lychee', 'color_hex' => '#CCCCCC', 'sort_order' => 303]);
        Color::updateOrCreate(['color_code' => '404396'], ['color_name' => 'Lychee-Blaze', 'color_hex' => '#CCCCCC', 'sort_order' => 304]);
        Color::updateOrCreate(['color_code' => '410000'], ['color_name' => 'Crush', 'color_hex' => '#CCCCCC', 'sort_order' => 305]);
        Color::updateOrCreate(['color_code' => '414000'], ['color_name' => 'Rose', 'color_hex' => '#CCCCCC', 'sort_order' => 306]);
        Color::updateOrCreate(['color_code' => '430000'], ['color_name' => 'Bright Red', 'color_hex' => '#CCCCCC', 'sort_order' => 307]);
        Color::updateOrCreate(['color_code' => '430390'], ['color_name' => 'Bright Red/Navy', 'color_hex' => '#CCCCCC', 'sort_order' => 308]);
        Color::updateOrCreate(['color_code' => '430900'], ['color_name' => 'Bright Red/White', 'color_hex' => '#CCCCCC', 'sort_order' => 309]);
        Color::updateOrCreate(['color_code' => '430999'], ['color_name' => 'Bright Red/Black', 'color_hex' => '#CCCCCC', 'sort_order' => 310]);
        Color::updateOrCreate(['color_code' => '433000'], ['color_name' => 'Fiesta', 'color_hex' => '#CCCCCC', 'sort_order' => 311]);
        Color::updateOrCreate(['color_code' => '478000'], ['color_name' => 'Berry', 'color_hex' => '#CCCCCC', 'sort_order' => 312]);
        Color::updateOrCreate(['color_code' => '479000'], ['color_name' => 'Machine', 'color_hex' => '#CCCCCC', 'sort_order' => 313]);
        Color::updateOrCreate(['color_code' => '479488'], ['color_name' => 'Machine-Rhubarb', 'color_hex' => '#CCCCCC', 'sort_order' => 314]);
        Color::updateOrCreate(['color_code' => '479738'], ['color_name' => 'Machine-Fame', 'color_hex' => '#CCCCCC', 'sort_order' => 315]);
        Color::updateOrCreate(['color_code' => '480710'], ['color_name' => 'Peak-Hint', 'color_hex' => '#CCCCCC', 'sort_order' => 316]);
        Color::updateOrCreate(['color_code' => '488000'], ['color_name' => 'Rhubarb', 'color_hex' => '#CCCCCC', 'sort_order' => 317]);
        Color::updateOrCreate(['color_code' => '488718'], ['color_name' => 'Rhubarb-Gum', 'color_hex' => '#CCCCCC', 'sort_order' => 318]);
        Color::updateOrCreate(['color_code' => '500000'], ['color_name' => 'Tawny', 'color_hex' => '#CCCCCC', 'sort_order' => 319]);
        Color::updateOrCreate(['color_code' => '503000'], ['color_name' => 'N Light', 'color_hex' => '#CCCCCC', 'sort_order' => 320]);
        Color::updateOrCreate(['color_code' => '552000'], ['color_name' => 'Sweden Yellow', 'color_hex' => '#CCCCCC', 'sort_order' => 321]);
        Color::updateOrCreate(['color_code' => '552851'], ['color_name' => 'Sweden Yellow/Flumino', 'color_hex' => '#CCCCCC', 'sort_order' => 322]);
        Color::updateOrCreate(['color_code' => '552999'], ['color_name' => 'Sweden Yellow/Black', 'color_hex' => '#CCCCCC', 'sort_order' => 323]);
        Color::updateOrCreate(['color_code' => '560000'], ['color_name' => 'Tiger', 'color_hex' => '#CCCCCC', 'sort_order' => 324]);
        Color::updateOrCreate(['color_code' => '560200'], ['color_name' => 'Tiger Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 325]);
        Color::updateOrCreate(['color_code' => '560995'], ['color_name' => 'Tiger-Asphalt', 'color_hex' => '#CCCCCC', 'sort_order' => 326]);
        Color::updateOrCreate(['color_code' => '568999'], ['color_name' => 'Carrot/Black', 'color_hex' => '#CCCCCC', 'sort_order' => 327]);
        Color::updateOrCreate(['color_code' => '575000'], ['color_name' => 'Pump', 'color_hex' => '#CCCCCC', 'sort_order' => 328]);
        Color::updateOrCreate(['color_code' => '576000'], ['color_name' => 'Flourange', 'color_hex' => '#CCCCCC', 'sort_order' => 329]);
        Color::updateOrCreate(['color_code' => '577000'], ['color_name' => 'Pace', 'color_hex' => '#CCCCCC', 'sort_order' => 330]);
        Color::updateOrCreate(['color_code' => '578000'], ['color_name' => 'Orange Sun', 'color_hex' => '#CCCCCC', 'sort_order' => 331]);
        Color::updateOrCreate(['color_code' => '579000'], ['color_name' => 'Tart', 'color_hex' => '#CCCCCC', 'sort_order' => 332]);
        Color::updateOrCreate(['color_code' => '580580'], ['color_name' => 'Dark Navy Print', 'color_hex' => '#CCCCCC', 'sort_order' => 333]);
        Color::updateOrCreate(['color_code' => '606000'], ['color_name' => 'Craft Green', 'color_hex' => '#CCCCCC', 'sort_order' => 334]);
        Color::updateOrCreate(['color_code' => '609000'], ['color_name' => 'Neo', 'color_hex' => '#CCCCCC', 'sort_order' => 335]);
        Color::updateOrCreate(['color_code' => '613000'], ['color_name' => 'Trooper', 'color_hex' => '#CCCCCC', 'sort_order' => 336]);
        Color::updateOrCreate(['color_code' => '613503'], ['color_name' => 'Trooper-N Light', 'color_hex' => '#CCCCCC', 'sort_order' => 337]);
        Color::updateOrCreate(['color_code' => '613914'], ['color_name' => 'Trooper-Ash', 'color_hex' => '#CCCCCC', 'sort_order' => 338]);
        Color::updateOrCreate(['color_code' => '617000'], ['color_name' => 'Eon', 'color_hex' => '#CCCCCC', 'sort_order' => 339]);
        Color::updateOrCreate(['color_code' => '635851'], ['color_name' => 'Forest-Flumino', 'color_hex' => '#CCCCCC', 'sort_order' => 340]);
        Color::updateOrCreate(['color_code' => '645000'], ['color_name' => 'Scream', 'color_hex' => '#CCCCCC', 'sort_order' => 341]);
        Color::updateOrCreate(['color_code' => '648000'], ['color_name' => 'Dark Olive', 'color_hex' => '#CCCCCC', 'sort_order' => 342]);
        Color::updateOrCreate(['color_code' => '648560'], ['color_name' => 'Dark Olive-Tiger', 'color_hex' => '#CCCCCC', 'sort_order' => 343]);
        Color::updateOrCreate(['color_code' => '650000'], ['color_name' => 'Sencha', 'color_hex' => '#CCCCCC', 'sort_order' => 344]);
        Color::updateOrCreate(['color_code' => '651000'], ['color_name' => 'Team Green', 'color_hex' => '#CCCCCC', 'sort_order' => 345]);
        Color::updateOrCreate(['color_code' => '651606'], ['color_name' => 'Team Green/Craft Green', 'color_hex' => '#CCCCCC', 'sort_order' => 346]);
        Color::updateOrCreate(['color_code' => '651900'], ['color_name' => 'Team Green/White', 'color_hex' => '#CCCCCC', 'sort_order' => 347]);
        Color::updateOrCreate(['color_code' => '651999'], ['color_name' => 'Team Green/Black', 'color_hex' => '#CCCCCC', 'sort_order' => 348]);
        Color::updateOrCreate(['color_code' => '652000'], ['color_name' => 'Lazer', 'color_hex' => '#CCCCCC', 'sort_order' => 349]);
        Color::updateOrCreate(['color_code' => '664000'], ['color_name' => 'Rift', 'color_hex' => '#CCCCCC', 'sort_order' => 350]);
        Color::updateOrCreate(['color_code' => '669000'], ['color_name' => 'Woods', 'color_hex' => '#CCCCCC', 'sort_order' => 351]);
        Color::updateOrCreate(['color_code' => '669200'], ['color_name' => 'Woods Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 352]);
        Color::updateOrCreate(['color_code' => '676000'], ['color_name' => 'Universe', 'color_hex' => '#CCCCCC', 'sort_order' => 353]);
        Color::updateOrCreate(['color_code' => '676396'], ['color_name' => 'Universe-Blaze', 'color_hex' => '#CCCCCC', 'sort_order' => 354]);
        Color::updateOrCreate(['color_code' => '678000'], ['color_name' => 'Opal', 'color_hex' => '#CCCCCC', 'sort_order' => 355]);
        Color::updateOrCreate(['color_code' => '697000'], ['color_name' => 'Point', 'color_hex' => '#CCCCCC', 'sort_order' => 356]);
        Color::updateOrCreate(['color_code' => '697645'], ['color_name' => 'Point-Scream', 'color_hex' => '#CCCCCC', 'sort_order' => 357]);
        Color::updateOrCreate(['color_code' => '699000'], ['color_name' => 'Buff', 'color_hex' => '#CCCCCC', 'sort_order' => 358]);
        Color::updateOrCreate(['color_code' => '710000'], ['color_name' => 'Hint', 'color_hex' => '#CCCCCC', 'sort_order' => 359]);
        Color::updateOrCreate(['color_code' => '710480'], ['color_name' => 'Hint-Peak', 'color_hex' => '#CCCCCC', 'sort_order' => 360]);
        Color::updateOrCreate(['color_code' => '717000'], ['color_name' => 'Nude', 'color_hex' => '#CCCCCC', 'sort_order' => 361]);
        Color::updateOrCreate(['color_code' => '718000'], ['color_name' => 'Gum', 'color_hex' => '#CCCCCC', 'sort_order' => 362]);
        Color::updateOrCreate(['color_code' => '736000'], ['color_name' => 'Hot Pink', 'color_hex' => '#CCCCCC', 'sort_order' => 363]);
        Color::updateOrCreate(['color_code' => '737000'], ['color_name' => 'Trace', 'color_hex' => '#CCCCCC', 'sort_order' => 364]);
        Color::updateOrCreate(['color_code' => '737349'], ['color_name' => 'Trace-Beat', 'color_hex' => '#CCCCCC', 'sort_order' => 365]);
        Color::updateOrCreate(['color_code' => '738000'], ['color_name' => 'Fame', 'color_hex' => '#CCCCCC', 'sort_order' => 366]);
        Color::updateOrCreate(['color_code' => '738479'], ['color_name' => 'Fame-Machine', 'color_hex' => '#CCCCCC', 'sort_order' => 367]);
        Color::updateOrCreate(['color_code' => '738645'], ['color_name' => 'Fame-Scream', 'color_hex' => '#CCCCCC', 'sort_order' => 368]);
        Color::updateOrCreate(['color_code' => '738738'], ['color_name' => 'Fame-Fame', 'color_hex' => '#CCCCCC', 'sort_order' => 369]);
        Color::updateOrCreate(['color_code' => '740579'], ['color_name' => 'Coral-Tart', 'color_hex' => '#CCCCCC', 'sort_order' => 370]);
        Color::updateOrCreate(['color_code' => '801000'], ['color_name' => 'Panic', 'color_hex' => '#CCCCCC', 'sort_order' => 371]);
        Color::updateOrCreate(['color_code' => '809000'], ['color_name' => 'Snap', 'color_hex' => '#CCCCCC', 'sort_order' => 372]);
        Color::updateOrCreate(['color_code' => '810000'], ['color_name' => 'Gecko', 'color_hex' => '#CCCCCC', 'sort_order' => 373]);
        Color::updateOrCreate(['color_code' => '825000'], ['color_name' => 'Shock', 'color_hex' => '#CCCCCC', 'sort_order' => 374]);
        Color::updateOrCreate(['color_code' => '845000'], ['color_name' => 'Neon Blaze', 'color_hex' => '#CCCCCC', 'sort_order' => 375]);
        Color::updateOrCreate(['color_code' => '851000'], ['color_name' => 'Flumino', 'color_hex' => '#CCCCCC', 'sort_order' => 376]);
        Color::updateOrCreate(['color_code' => '851999'], ['color_name' => 'Flumino-Black', 'color_hex' => '#CCCCCC', 'sort_order' => 377]);
        Color::updateOrCreate(['color_code' => '900000'], ['color_name' => 'White', 'color_hex' => '#CCCCCC', 'sort_order' => 378]);
        Color::updateOrCreate(['color_code' => '900346'], ['color_name' => 'White/Club Cobolt', 'color_hex' => '#CCCCCC', 'sort_order' => 379]);
        Color::updateOrCreate(['color_code' => '900360'], ['color_name' => 'White/Burst', 'color_hex' => '#CCCCCC', 'sort_order' => 380]);
        Color::updateOrCreate(['color_code' => '900430'], ['color_name' => 'White/Bright Red', 'color_hex' => '#CCCCCC', 'sort_order' => 381]);
        Color::updateOrCreate(['color_code' => '900651'], ['color_name' => 'White/Team Green', 'color_hex' => '#CCCCCC', 'sort_order' => 382]);
        Color::updateOrCreate(['color_code' => '900926'], ['color_name' => 'White/Silver', 'color_hex' => '#CCCCCC', 'sort_order' => 383]);
        Color::updateOrCreate(['color_code' => '900999'], ['color_name' => 'White/Black', 'color_hex' => '#CCCCCC', 'sort_order' => 384]);
        Color::updateOrCreate(['color_code' => '914000'], ['color_name' => 'Ash', 'color_hex' => '#CCCCCC', 'sort_order' => 385]);
        Color::updateOrCreate(['color_code' => '914567'], ['color_name' => 'Ash/Vermello', 'color_hex' => '#CCCCCC', 'sort_order' => 386]);
        Color::updateOrCreate(['color_code' => '914645'], ['color_name' => 'Ash/Scream', 'color_hex' => '#CCCCCC', 'sort_order' => 387]);
        Color::updateOrCreate(['color_code' => '914985'], ['color_name' => 'Ash/Granite', 'color_hex' => '#CCCCCC', 'sort_order' => 388]);
        Color::updateOrCreate(['color_code' => '914999'], ['color_name' => 'Ash-Black', 'color_hex' => '#CCCCCC', 'sort_order' => 389]);
        Color::updateOrCreate(['color_code' => '916000'], ['color_name' => 'Shade', 'color_hex' => '#CCCCCC', 'sort_order' => 390]);
        Color::updateOrCreate(['color_code' => '920000'], ['color_name' => 'Platinum', 'color_hex' => '#CCCCCC', 'sort_order' => 391]);
        Color::updateOrCreate(['color_code' => '926999'], ['color_name' => 'Silver-Black', 'color_hex' => '#CCCCCC', 'sort_order' => 392]);
        Color::updateOrCreate(['color_code' => '935000'], ['color_name' => 'Monument', 'color_hex' => '#CCCCCC', 'sort_order' => 393]);
        Color::updateOrCreate(['color_code' => '947200'], ['color_name' => 'Gravel Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 394]);
        Color::updateOrCreate(['color_code' => '947563'], ['color_name' => 'Gravel/Sprint', 'color_hex' => '#CCCCCC', 'sort_order' => 395]);
        Color::updateOrCreate(['color_code' => '950000'], ['color_name' => 'Grey Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 396]);
        Color::updateOrCreate(['color_code' => '975000'], ['color_name' => 'Dk Grey Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 397]);
        Color::updateOrCreate(['color_code' => '981000'], ['color_name' => 'Smoked Pearl', 'color_hex' => '#CCCCCC', 'sort_order' => 398]);
        Color::updateOrCreate(['color_code' => '985000'], ['color_name' => 'Granite', 'color_hex' => '#CCCCCC', 'sort_order' => 399]);
        Color::updateOrCreate(['color_code' => '985920'], ['color_name' => 'Granite-Platinum', 'color_hex' => '#CCCCCC', 'sort_order' => 400]);
        Color::updateOrCreate(['color_code' => '995000'], ['color_name' => 'Asphalt', 'color_hex' => '#CCCCCC', 'sort_order' => 401]);
        Color::updateOrCreate(['color_code' => '995480'], ['color_name' => 'Asphalt-Peak', 'color_hex' => '#CCCCCC', 'sort_order' => 402]);
        Color::updateOrCreate(['color_code' => '995900'], ['color_name' => 'Asphalt-White', 'color_hex' => '#CCCCCC', 'sort_order' => 403]);
        Color::updateOrCreate(['color_code' => '998000'], ['color_name' => 'Black Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 404]);
        Color::updateOrCreate(['color_code' => '998999'], ['color_name' => 'Black Melange/Black', 'color_hex' => '#CCCCCC', 'sort_order' => 405]);
        Color::updateOrCreate(['color_code' => '999000'], ['color_name' => 'Black', 'color_hex' => '#CCCCCC', 'sort_order' => 406]);
        Color::updateOrCreate(['color_code' => '999346'], ['color_name' => 'Black/Club Cobolt', 'color_hex' => '#CCCCCC', 'sort_order' => 407]);
        Color::updateOrCreate(['color_code' => '999430'], ['color_name' => 'Black/Bright Red', 'color_hex' => '#CCCCCC', 'sort_order' => 408]);
        Color::updateOrCreate(['color_code' => '999552'], ['color_name' => 'Black/Sweden Yellow', 'color_hex' => '#CCCCCC', 'sort_order' => 409]);
        Color::updateOrCreate(['color_code' => '999577'], ['color_name' => 'Black/Pace', 'color_hex' => '#CCCCCC', 'sort_order' => 410]);
        Color::updateOrCreate(['color_code' => '999651'], ['color_name' => 'Black/Team Green', 'color_hex' => '#CCCCCC', 'sort_order' => 411]);
        Color::updateOrCreate(['color_code' => '999851'], ['color_name' => 'Black-Flumino', 'color_hex' => '#CCCCCC', 'sort_order' => 412]);
        Color::updateOrCreate(['color_code' => '999900'], ['color_name' => 'Black/White', 'color_hex' => '#CCCCCC', 'sort_order' => 413]);
        Color::updateOrCreate(['color_code' => '999914'], ['color_name' => 'Black-Ash', 'color_hex' => '#CCCCCC', 'sort_order' => 414]);
        Color::updateOrCreate(['color_code' => '999920'], ['color_name' => 'Black/Platinum', 'color_hex' => '#CCCCCC', 'sort_order' => 415]);
        Color::updateOrCreate(['color_code' => '999926'], ['color_name' => 'Black-Silver', 'color_hex' => '#CCCCCC', 'sort_order' => 416]);
        Color::updateOrCreate(['color_code' => '999975'], ['color_name' => 'Black-Dk Grey Melange', 'color_hex' => '#CCCCCC', 'sort_order' => 417]);
        Color::updateOrCreate(['color_code' => '999985'], ['color_name' => 'Black-Granite', 'color_hex' => '#CCCCCC', 'sort_order' => 418]);
        Color::updateOrCreate(['color_code' => '999995'], ['color_name' => 'Black-Asphalt', 'color_hex' => '#CCCCCC', 'sort_order' => 419]);
        Color::updateOrCreate(['color_code' => '999999'], ['color_name' => 'Black/Black', 'color_hex' => '#CCCCCC', 'sort_order' => 420]);
        Color::updateOrCreate(['color_code' => 'B396000'], ['color_name' => 'Blaze', 'color_hex' => '#CCCCCC', 'sort_order' => 421]);
        Color::updateOrCreate(['color_code' => 'B404000'], ['color_name' => 'Lychee', 'color_hex' => '#CCCCCC', 'sort_order' => 422]);
        Color::updateOrCreate(['color_code' => 'B500000'], ['color_name' => 'Tawny', 'color_hex' => '#CCCCCC', 'sort_order' => 423]);
        Color::updateOrCreate(['color_code' => 'B613000'], ['color_name' => 'Trooper', 'color_hex' => '#CCCCCC', 'sort_order' => 424]);
        Color::updateOrCreate(['color_code' => 'B676000'], ['color_name' => 'Universe', 'color_hex' => '#CCCCCC', 'sort_order' => 425]);
        Color::updateOrCreate(['color_code' => 'B738000'], ['color_name' => 'Fame', 'color_hex' => '#CCCCCC', 'sort_order' => 426]);
        Color::updateOrCreate(['color_code' => 'B999000'], ['color_name' => 'Black', 'color_hex' => '#CCCCCC', 'sort_order' => 427]);
        Color::updateOrCreate(['color_code' => 'X999995'], ['color_name' => 'Black-Asphalt', 'color_hex' => '#CCCCCC', 'sort_order' => 428]);
    }
        $this->call(NewWaveProductSeeder::class);
    }
}
