<?php

namespace Database\Seeders;

use App\Models\Size;

use Illuminate\Database\Seeder;

class SizeSeeder extends Seeder
{
    public function run(): void
    {
                // Seed Sizes
        Size::updateOrCreate(['size' => 'XXS', 'size_code' => '2'], ['size_name' => 'XXS', 'sort_order' => 1]);
        Size::updateOrCreate(['size' => 'XS', 'size_code' => '3'], ['size_name' => 'XS', 'sort_order' => 2]);
        Size::updateOrCreate(['size' => 'UK 03', 'size_code' => '03'], ['size_name' => 'UK 03', 'sort_order' => 3]);
        Size::updateOrCreate(['size' => 'S', 'size_code' => '4'], ['size_name' => 'S', 'sort_order' => 4]);
        Size::updateOrCreate(['size' => 'UK 04', 'size_code' => '04'], ['size_name' => 'UK 04', 'sort_order' => 5]);
        Size::updateOrCreate(['size' => 'M', 'size_code' => '5'], ['size_name' => 'M', 'sort_order' => 6]);
        Size::updateOrCreate(['size' => 'UK 05', 'size_code' => '05'], ['size_name' => 'UK 05', 'sort_order' => 7]);
        Size::updateOrCreate(['size' => 'L', 'size_code' => '6'], ['size_name' => 'L', 'sort_order' => 8]);
        Size::updateOrCreate(['size' => 'UK 06', 'size_code' => '06'], ['size_name' => 'UK 06', 'sort_order' => 9]);
        Size::updateOrCreate(['size' => 'XL', 'size_code' => '7'], ['size_name' => 'XL', 'sort_order' => 10]);
        Size::updateOrCreate(['size' => 'UK 07', 'size_code' => '07'], ['size_name' => 'UK 07', 'sort_order' => 11]);
        Size::updateOrCreate(['size' => 'XXL', 'size_code' => '8'], ['size_name' => 'XXL', 'sort_order' => 12]);
        Size::updateOrCreate(['size' => 'UK 08', 'size_code' => '08'], ['size_name' => 'UK 08', 'sort_order' => 13]);
        Size::updateOrCreate(['size' => '3XL', 'size_code' => '9'], ['size_name' => '3XL', 'sort_order' => 14]);
        Size::updateOrCreate(['size' => 'UK 09', 'size_code' => '09'], ['size_name' => 'UK 09', 'sort_order' => 15]);
        Size::updateOrCreate(['size' => '4XL', 'size_code' => '10'], ['size_name' => '4XL', 'sort_order' => 16]);
        Size::updateOrCreate(['size' => 'UK 10,5', 'size_code' => '10,5'], ['size_name' => 'UK 10,5', 'sort_order' => 17]);
        Size::updateOrCreate(['size' => '5XL', 'size_code' => '11'], ['size_name' => '5XL', 'sort_order' => 18]);
        Size::updateOrCreate(['size' => 'UK 11,5', 'size_code' => '11,5'], ['size_name' => 'UK 11,5', 'sort_order' => 19]);
        Size::updateOrCreate(['size' => '6XL', 'size_code' => '12'], ['size_name' => '6XL', 'sort_order' => 20]);
        Size::updateOrCreate(['size' => 'UK 12,5', 'size_code' => '12,5'], ['size_name' => 'UK 12,5', 'sort_order' => 21]);
        Size::updateOrCreate(['size' => 'UK 13', 'size_code' => '13'], ['size_name' => 'UK 13', 'sort_order' => 22]);
        Size::updateOrCreate(['size' => 'UK 14', 'size_code' => '14'], ['size_name' => 'UK 14', 'sort_order' => 23]);
        Size::updateOrCreate(['size' => 'UK 15', 'size_code' => '15'], ['size_name' => 'UK 15', 'sort_order' => 24]);
        Size::updateOrCreate(['size' => '28/30', 'size_code' => '28'], ['size_name' => '28/30', 'sort_order' => 25]);
        Size::updateOrCreate(['size' => '30"', 'size_code' => '30'], ['size_name' => '30"', 'sort_order' => 26]);
        Size::updateOrCreate(['size' => '31"', 'size_code' => '31'], ['size_name' => '31"', 'sort_order' => 27]);
        Size::updateOrCreate(['size' => 'C32', 'size_code' => '32'], ['size_name' => 'C32', 'sort_order' => 28]);
        Size::updateOrCreate(['size' => '33"', 'size_code' => '33'], ['size_name' => '33"', 'sort_order' => 29]);
        Size::updateOrCreate(['size' => 'C34', 'size_code' => '34'], ['size_name' => 'C34', 'sort_order' => 30]);
        Size::updateOrCreate(['size' => '35-37', 'size_code' => '35'], ['size_name' => '35-37', 'sort_order' => 31]);
        Size::updateOrCreate(['size' => 'C36', 'size_code' => '36'], ['size_name' => 'C36', 'sort_order' => 32]);
        Size::updateOrCreate(['size' => 'SIZE 37', 'size_code' => '37'], ['size_name' => 'SIZE 37', 'sort_order' => 33]);
        Size::updateOrCreate(['size' => 'C38', 'size_code' => '38'], ['size_name' => 'C38', 'sort_order' => 34]);
        Size::updateOrCreate(['size' => 'SIZE 39', 'size_code' => '39'], ['size_name' => 'SIZE 39', 'sort_order' => 35]);
        Size::updateOrCreate(['size' => 'C40', 'size_code' => '40'], ['size_name' => 'C40', 'sort_order' => 36]);
        Size::updateOrCreate(['size' => 'SIZE 41', 'size_code' => '41'], ['size_name' => 'SIZE 41', 'sort_order' => 37]);
        Size::updateOrCreate(['size' => 'C42', 'size_code' => '42'], ['size_name' => 'C42', 'sort_order' => 38]);
        Size::updateOrCreate(['size' => 'SIZE 43', 'size_code' => '43'], ['size_name' => 'SIZE 43', 'sort_order' => 39]);
        Size::updateOrCreate(['size' => 'C44', 'size_code' => '44'], ['size_name' => 'C44', 'sort_order' => 40]);
        Size::updateOrCreate(['size' => 'SIZE 45', 'size_code' => '45'], ['size_name' => 'SIZE 45', 'sort_order' => 41]);
        Size::updateOrCreate(['size' => 'C46', 'size_code' => '46'], ['size_name' => 'C46', 'sort_order' => 42]);
        Size::updateOrCreate(['size' => 'SIZE 47', 'size_code' => '47'], ['size_name' => 'SIZE 47', 'sort_order' => 43]);
        Size::updateOrCreate(['size' => 'C48', 'size_code' => '48'], ['size_name' => 'C48', 'sort_order' => 44]);
        Size::updateOrCreate(['size' => 'C50', 'size_code' => '50'], ['size_name' => 'C50', 'sort_order' => 45]);
        Size::updateOrCreate(['size' => 'C52', 'size_code' => '52'], ['size_name' => 'C52', 'sort_order' => 46]);
        Size::updateOrCreate(['size' => 'C54', 'size_code' => '54'], ['size_name' => 'C54', 'sort_order' => 47]);
        Size::updateOrCreate(['size' => 'C56', 'size_code' => '56'], ['size_name' => 'C56', 'sort_order' => 48]);
        Size::updateOrCreate(['size' => 'C58', 'size_code' => '58'], ['size_name' => 'C58', 'sort_order' => 49]);
        Size::updateOrCreate(['size' => 'C60', 'size_code' => '60'], ['size_name' => 'C60', 'sort_order' => 50]);
        Size::updateOrCreate(['size' => 'C62', 'size_code' => '62'], ['size_name' => 'C62', 'sort_order' => 51]);
        Size::updateOrCreate(['size' => 'C64', 'size_code' => '64'], ['size_name' => 'C64', 'sort_order' => 52]);
        Size::updateOrCreate(['size' => '85 CM.', 'size_code' => '70'], ['size_name' => '85 CM.', 'sort_order' => 53]);
        Size::updateOrCreate(['size' => 'D84', 'size_code' => '84'], ['size_name' => 'D84', 'sort_order' => 54]);
        Size::updateOrCreate(['size' => '100 CM.', 'size_code' => '85'], ['size_name' => '100 CM.', 'sort_order' => 55]);
        Size::updateOrCreate(['size' => 'D88', 'size_code' => '88'], ['size_name' => 'D88', 'sort_order' => 56]);
        Size::updateOrCreate(['size' => 'D92', 'size_code' => '92'], ['size_name' => 'D92', 'sort_order' => 57]);
        Size::updateOrCreate(['size' => '110 CM.', 'size_code' => '95'], ['size_name' => '110 CM.', 'sort_order' => 58]);
        Size::updateOrCreate(['size' => 'D96', 'size_code' => '96'], ['size_name' => 'D96', 'sort_order' => 59]);
        Size::updateOrCreate(['size' => 'D100', 'size_code' => '100'], ['size_name' => 'D100', 'sort_order' => 60]);
        Size::updateOrCreate(['size' => 'D104', 'size_code' => '104'], ['size_name' => 'D104', 'sort_order' => 61]);
        Size::updateOrCreate(['size' => '105 CM', 'size_code' => '105'], ['size_name' => '105 CM', 'sort_order' => 62]);
        Size::updateOrCreate(['size' => 'D108', 'size_code' => '108'], ['size_name' => 'D108', 'sort_order' => 63]);
        Size::updateOrCreate(['size' => '110/116', 'size_code' => '110'], ['size_name' => '110/116', 'sort_order' => 64]);
        Size::updateOrCreate(['size' => 'D112', 'size_code' => '112'], ['size_name' => 'D112', 'sort_order' => 65]);
        Size::updateOrCreate(['size' => 'D116', 'size_code' => '116'], ['size_name' => 'D116', 'sort_order' => 66]);
        Size::updateOrCreate(['size' => 'D120', 'size_code' => '120'], ['size_name' => 'D120', 'sort_order' => 67]);
        Size::updateOrCreate(['size' => '122/128', 'size_code' => '122'], ['size_name' => '122/128', 'sort_order' => 68]);
        Size::updateOrCreate(['size' => '122/128', 'size_code' => '128'], ['size_name' => '122/128', 'sort_order' => 69]);
        Size::updateOrCreate(['size' => 'UK 13,5', 'size_code' => '13,5'], ['size_name' => 'UK 13,5', 'sort_order' => 70]);
        Size::updateOrCreate(['size' => '134/140', 'size_code' => '134'], ['size_name' => '134/140', 'sort_order' => 71]);
        Size::updateOrCreate(['size' => '130/140', 'size_code' => '140'], ['size_name' => '130/140', 'sort_order' => 72]);
        Size::updateOrCreate(['size' => 'C142', 'size_code' => '142'], ['size_name' => 'C142', 'sort_order' => 73]);
        Size::updateOrCreate(['size' => 'C144', 'size_code' => '144'], ['size_name' => 'C144', 'sort_order' => 74]);
        Size::updateOrCreate(['size' => 'C146', 'size_code' => '146'], ['size_name' => 'C146', 'sort_order' => 75]);
        Size::updateOrCreate(['size' => 'C148', 'size_code' => '148'], ['size_name' => 'C148', 'sort_order' => 76]);
        Size::updateOrCreate(['size' => 'C150', 'size_code' => '150'], ['size_name' => 'C150', 'sort_order' => 77]);
        Size::updateOrCreate(['size' => 'C152', 'size_code' => '152'], ['size_name' => 'C152', 'sort_order' => 78]);
        Size::updateOrCreate(['size' => 'C154', 'size_code' => '154'], ['size_name' => 'C154', 'sort_order' => 79]);
        Size::updateOrCreate(['size' => 'C156', 'size_code' => '156'], ['size_name' => 'C156', 'sort_order' => 80]);
        Size::updateOrCreate(['size' => '158/164', 'size_code' => '158'], ['size_name' => '158/164', 'sort_order' => 81]);
        Size::updateOrCreate(['size' => 'C160', 'size_code' => '160'], ['size_name' => 'C160', 'sort_order' => 82]);
        Size::updateOrCreate(['size' => 'C162', 'size_code' => '162'], ['size_name' => 'C162', 'sort_order' => 83]);
        Size::updateOrCreate(['size' => 'C164', 'size_code' => '164'], ['size_name' => 'C164', 'sort_order' => 84]);
        Size::updateOrCreate(['size' => '25/32', 'size_code' => '2532'], ['size_name' => '25/32', 'sort_order' => 85]);
        Size::updateOrCreate(['size' => '25/34', 'size_code' => '2534'], ['size_name' => '25/34', 'sort_order' => 86]);
        Size::updateOrCreate(['size' => '26/32', 'size_code' => '2632'], ['size_name' => '26/32', 'sort_order' => 87]);
        Size::updateOrCreate(['size' => '26/34', 'size_code' => '2634'], ['size_name' => '26/34', 'sort_order' => 88]);
        Size::updateOrCreate(['size' => '28/30', 'size_code' => '2830'], ['size_name' => '28/30', 'sort_order' => 89]);
        Size::updateOrCreate(['size' => '28/32', 'size_code' => '2832'], ['size_name' => '28/32', 'sort_order' => 90]);
        Size::updateOrCreate(['size' => '28/34', 'size_code' => '2834'], ['size_name' => '28/34', 'sort_order' => 91]);
        Size::updateOrCreate(['size' => '29/30', 'size_code' => '2930'], ['size_name' => '29/30', 'sort_order' => 92]);
        Size::updateOrCreate(['size' => '29/32', 'size_code' => '2932'], ['size_name' => '29/32', 'sort_order' => 93]);
        Size::updateOrCreate(['size' => '29/34', 'size_code' => '2934'], ['size_name' => '29/34', 'sort_order' => 94]);
        Size::updateOrCreate(['size' => 'UK 3,5', 'size_code' => '3,5'], ['size_name' => 'UK 3,5', 'sort_order' => 95]);
        Size::updateOrCreate(['size' => '30/30', 'size_code' => '3030'], ['size_name' => '30/30', 'sort_order' => 96]);
        Size::updateOrCreate(['size' => '30/32', 'size_code' => '3032'], ['size_name' => '30/32', 'sort_order' => 97]);
        Size::updateOrCreate(['size' => '30/34', 'size_code' => '3034'], ['size_name' => '30/34', 'sort_order' => 98]);
        Size::updateOrCreate(['size' => '31/30', 'size_code' => '3130'], ['size_name' => '31/30', 'sort_order' => 99]);
        Size::updateOrCreate(['size' => '31/32', 'size_code' => '3132'], ['size_name' => '31/32', 'sort_order' => 100]);
        Size::updateOrCreate(['size' => '31/34', 'size_code' => '3134'], ['size_name' => '31/34', 'sort_order' => 101]);
        Size::updateOrCreate(['size' => '32/30', 'size_code' => '3230'], ['size_name' => '32/30', 'sort_order' => 102]);
        Size::updateOrCreate(['size' => '32/32', 'size_code' => '3232'], ['size_name' => '32/32', 'sort_order' => 103]);
        Size::updateOrCreate(['size' => '32/34', 'size_code' => '3234'], ['size_name' => '32/34', 'sort_order' => 104]);
        Size::updateOrCreate(['size' => '32/36', 'size_code' => '3236'], ['size_name' => '32/36', 'sort_order' => 105]);
        Size::updateOrCreate(['size' => '33/30', 'size_code' => '3330'], ['size_name' => '33/30', 'sort_order' => 106]);
        Size::updateOrCreate(['size' => '33/32', 'size_code' => '3332'], ['size_name' => '33/32', 'sort_order' => 107]);
        Size::updateOrCreate(['size' => '33/34', 'size_code' => '3334'], ['size_name' => '33/34', 'sort_order' => 108]);
        Size::updateOrCreate(['size' => '33/36', 'size_code' => '3336'], ['size_name' => '33/36', 'sort_order' => 109]);
        Size::updateOrCreate(['size' => '34/30', 'size_code' => '3430'], ['size_name' => '34/30', 'sort_order' => 110]);
        Size::updateOrCreate(['size' => '34/32', 'size_code' => '3432'], ['size_name' => '34/32', 'sort_order' => 111]);
        Size::updateOrCreate(['size' => '34/34', 'size_code' => '3434'], ['size_name' => '34/34', 'sort_order' => 112]);
        Size::updateOrCreate(['size' => '34/36', 'size_code' => '3436'], ['size_name' => '34/36', 'sort_order' => 113]);
        Size::updateOrCreate(['size' => '35-38', 'size_code' => '3538'], ['size_name' => '35-38', 'sort_order' => 114]);
        Size::updateOrCreate(['size' => '36/30', 'size_code' => '3630'], ['size_name' => '36/30', 'sort_order' => 115]);
        Size::updateOrCreate(['size' => '36/32', 'size_code' => '3632'], ['size_name' => '36/32', 'sort_order' => 116]);
        Size::updateOrCreate(['size' => '36/34', 'size_code' => '3634'], ['size_name' => '36/34', 'sort_order' => 117]);
        Size::updateOrCreate(['size' => '36/36', 'size_code' => '3636'], ['size_name' => '36/36', 'sort_order' => 118]);
        Size::updateOrCreate(['size' => '36-39', 'size_code' => '3639'], ['size_name' => '36-39', 'sort_order' => 119]);
        Size::updateOrCreate(['size' => '38/30', 'size_code' => '3830'], ['size_name' => '38/30', 'sort_order' => 120]);
        Size::updateOrCreate(['size' => '38/32', 'size_code' => '3832'], ['size_name' => '38/32', 'sort_order' => 121]);
        Size::updateOrCreate(['size' => '38/34', 'size_code' => '3834'], ['size_name' => '38/34', 'sort_order' => 122]);
        Size::updateOrCreate(['size' => '38/36', 'size_code' => '3836'], ['size_name' => '38/36', 'sort_order' => 123]);
        Size::updateOrCreate(['size' => '39-42', 'size_code' => '3942'], ['size_name' => '39-42', 'sort_order' => 124]);
        Size::updateOrCreate(['size' => 'UK 4,5', 'size_code' => '4,5'], ['size_name' => 'UK 4,5', 'sort_order' => 125]);
        Size::updateOrCreate(['size' => '40/32', 'size_code' => '4032'], ['size_name' => '40/32', 'sort_order' => 126]);
        Size::updateOrCreate(['size' => '40/34', 'size_code' => '4034'], ['size_name' => '40/34', 'sort_order' => 127]);
        Size::updateOrCreate(['size' => '40/36', 'size_code' => '4036'], ['size_name' => '40/36', 'sort_order' => 128]);
        Size::updateOrCreate(['size' => '40-42', 'size_code' => '4042'], ['size_name' => '40-42', 'sort_order' => 129]);
        Size::updateOrCreate(['size' => '4045', 'size_code' => '4045'], ['size_name' => '4045', 'sort_order' => 130]);
        Size::updateOrCreate(['size' => '42/32', 'size_code' => '4232'], ['size_name' => '42/32', 'sort_order' => 131]);
        Size::updateOrCreate(['size' => '4234', 'size_code' => '4234'], ['size_name' => '4234', 'sort_order' => 132]);
        Size::updateOrCreate(['size' => '4236', 'size_code' => '4236'], ['size_name' => '4236', 'sort_order' => 133]);
        Size::updateOrCreate(['size' => '43-45', 'size_code' => '4345'], ['size_name' => '43-45', 'sort_order' => 134]);
        Size::updateOrCreate(['size' => '43-46', 'size_code' => '4346'], ['size_name' => '43-46', 'sort_order' => 135]);
        Size::updateOrCreate(['size' => '46-48', 'size_code' => '4648'], ['size_name' => '46-48', 'sort_order' => 136]);
        Size::updateOrCreate(['size' => 'UK 5,5', 'size_code' => '5,5'], ['size_name' => 'UK 5,5', 'sort_order' => 137]);
        Size::updateOrCreate(['size' => 'UK 6,5', 'size_code' => '6,5'], ['size_name' => 'UK 6,5', 'sort_order' => 138]);
        Size::updateOrCreate(['size' => 'UK 7,5', 'size_code' => '7,5'], ['size_name' => 'UK 7,5', 'sort_order' => 139]);
        Size::updateOrCreate(['size' => 'UK 8,5', 'size_code' => '8,5'], ['size_name' => 'UK 8,5', 'sort_order' => 140]);
        Size::updateOrCreate(['size' => 'UK 9,5', 'size_code' => '9,5'], ['size_name' => 'UK 9,5', 'sort_order' => 141]);
        Size::updateOrCreate(['size' => 'L/XL', 'size_code' => 'L/XL'], ['size_name' => 'L/XL', 'sort_order' => 142]);
        Size::updateOrCreate(['size' => 'S/M', 'size_code' => 'S/M'], ['size_name' => 'S/M', 'sort_order' => 143]);
        Size::updateOrCreate(['size' => 'S_SWEA', 'size_code' => 'S_SWEA'], ['size_name' => 'S_SWEA', 'sort_order' => 144]);

 }
}
